NEW: Field formatting API, forward compatibility
silverstripe/silverstripe-graphql pull request #313
Opened 2020-11-02 03:21 UTC by unclecheese

Moved from: https://github.com/silverstripe/silverstripe-graphql/pull/310

2020-11-03 02:46 UTC, chillu requested changes
Looking good! Tested this with all the branches mentioned in https://github.com/silverstripe/silverstripe-graphql/issues/282. 

Talked with Aaron, we've agreed to mark the new API surface as `@internal` and encourage usage of GraphQL v4 instead.

We'll want to merge this close to the time as all the other PRs, since it would break common dev usage such as `silverstripe/cms:4.x-dev` + `silverstripe/graphql:3.x-dev` usage otherwise.

2020-11-04 03:50 UTC, chillu commented on src/Scaffolding/Scaffolders/DataObjectScaffolder.php
> +        parent::setUp();
This class doesn't have a parent?

2020-11-04 04:07 UTC, chillu commented on src/Pagination/Connection.php
> +            'nodes' => [
This breaks `admin/graphql/types/` when not running any of the associated PR branches.

```
GraphQL\Utils\Utils::invariant(, Schema must contain unique named types but contains multiple types named "Result" (see http://webonyx.github.io/graphql-php/type-system/#type-registry).)
TypeInfo.php:109
GraphQL\Utils\TypeInfo::extractTypes(Result, Array)
TypeInfo.php:94
GraphQL\Utils\TypeInfo::extractTypes([Result], Array)
TypeInfo.php:138
GraphQL\Utils\TypeInfo::extractTypes([Result], Array)
TypeInfo.php:138
GraphQL\Utils\TypeInfo::extractTypes(readFilesConnection, Array)
Schema.php:228
```

2020-11-04 04:10 UTC, chillu commented on src/Pagination/Connection.php
> +            'nodes' => [
`ReadFileQueryCreator->createConnection()` requires patching through it's own PR, which means this PR is coupled to the asset-admin one

2020-11-04 22:24 UTC, unclecheese commented on src/Scaffolding/Scaffolders/DataObjectScaffolder.php
> +        parent::setUp();
Ooof, looks like a copy-and-paste that was meant for `DataObjectScaffolderTest`. IDE fail.

2020-11-12 22:27 UTC, chillu commented on src/Pagination/Connection.php
> +            'nodes' => [
I don't think it's worth the effort to fix this just to avoid an hour of broken state in a pre-release branch while we merge everything else.

2020-11-12 22:28 UTC, chillu approved these changes

2020-11-13 01:34 UTC, merged