NEW: Stateless plugins, plugin registry as simple list
silverstripe/silverstripe-graphql pull request #327
Opened 2020-11-19 00:34 UTC by unclecheese

This fixes a number of errors that could come up when doing multiple schema builds where plugin state was polluted by preceding schemas. Plugins are no longer singletons, and are instead instantiated each time they are used. State that should be persisted for the duration of the build should be in static members, namespaced by the current schema.

2020-11-20 01:58 UTC, chillu requested changes

2020-11-20 01:58 UTC, chillu commented on src/Schema/Registry/PluginRegistry.php
> +            $inst = Injector::inst()->get($plugin);
Shouldn't this be `create()`? The idea was NOT to create singletons here, right? It's using `create()` further down in `getPluginByID()`

2020-11-20 01:58 UTC, chillu commented on _config/plugins.yml
> +      - 'SilverStripe\GraphQL\Schema\Plugin\PaginationPlugin'
We talked about using identifiers for plugins, rather than `Plugin->getIdentifier()`. It'd make it a bit more obvious how the YAML `plugins` config relates to actual class implementations. A nice side effect of this would be that users could *unregister* plugins from the registry, e.g. for security or performance reasons. And you could replace implementations by YAML config on `SilverStripe\GraphQL\Schema\Registry\PluginRegistry`, rather than the less obvious `Injector` config (dependency injection).

Admittedly, none of those arguments are particularly strong, so I'm happy to keep it as-is if you think that's the best way forward.

2020-11-23 01:03 UTC, unclecheese commented on _config/plugins.yml
> +      - 'SilverStripe\GraphQL\Schema\Plugin\PaginationPlugin'
Looked into this, and it's a bit complicated. There are just too many areas where a plugin needs to know its identifier internally, and discovering that from the config layer just seems really awkward.

The reason I got rid of the keys was because it's just confusing. We have too many of these arbitrary keys that don't mean anything. I was having a hard time envisioning a use case for cancelling out a plugin from the registry all together. 

What about an `excludePlugins` section?

2020-12-07 21:16 UTC, chillu commented on _config/plugins.yml
> +      - 'SilverStripe\GraphQL\Schema\Plugin\PaginationPlugin'
OK not worth it, we can always introduce `excludePlugins` later.

2020-12-07 21:17 UTC, chillu commented on src/Schema/Registry/PluginRegistry.php
> +            $inst = Injector::inst()->get($plugin);
It's a bit of a code smell, but since you're only using `getIdentifier()` on the instance it doesn't matter too much.

2020-12-07 21:17 UTC, chillu approved these changes

2020-12-07 21:17 UTC, merged