NEW: SchemaConfig layer, configuration overhaul
silverstripe/silverstripe-graphql pull request #329
Opened 2020-11-22 23:26 UTC by unclecheese

2020-11-27 03:12 UTC, chillu reviewed
Great work!

You still have `Injector::inst()->get(FilterRegistryInterface::class)` and `Injector::inst()->get(PluginRegistry::class)` in the code (so retrieving singletons). It doesn't appear that you can register new filters or plugins *by schema*, you can only apply already registered filters/plugins to aspects of your schema. Is that correct?

2020-11-27 03:14 UTC, chillu commented on src/Schema/Field/Field.php
>  use SilverStripe\GraphQL\Schema\Registry\ResolverRegistry;
You missed some `ResolverRegistry` references in this class

2020-11-27 04:18 UTC, chillu requested changes
Not quite sure what's going on, I can't get elemental or asset admin working with this. For example, the `readFiles` query doesn't discover the custom resolver, in the `.graphql/*` schema dump it points to the `DefaultResolver`. Running this config, which works fine without the forks.

```
{
    "name": "silverstripe/installer",
    "type": "silverstripe-recipe",
    "description": "The SilverStripe Framework Installer",
    "require": {
        "php": "^7.1 || ^8",
        "silverstripe/recipe-plugin": "^1.2",
        "silverstripe/recipe-cms": "4.x-dev",
        "silverstripe-themes/simple": "~3.2.0",
        "silverstripe/login-forms": "4.x-dev",
        "dnadesign/silverstripe-elemental": "dev-pulls/4/resolving-the-mystery as 4.x-dev",
        "silverstripe/mfa": "^4.2",
        "silverstripe/totp-authenticator": "^4.0",
        "silverstripe/graphql": "dev-pulls/master/resolving-the-mystery as 4.x-dev",
        "silverstripe/cms": "dev-pulls/4/resolving-the-mystery as 4.x-dev",
        "silverstripe/versioned": "dev-pulls/1/resolving-the-mystery as 1.x-dev",
        "silverstripe/asset-admin": "dev-pulls/1/resolving-the-mystery as 1.x-dev"
    },
    "require-dev": {
        "sminnee/phpunit": "^5.7",
        "silverstripe/graphql-devtools": "dev-master"
    },
    "extra": {
        "project-files": [
            "app/_config/*",
            ".env.example"
        ],
        "public-files": [
            "assets/*",
            "favicon.ico"
        ],
        "resources-dir": "_resources",
        "project-files-installed": [
            "app/src/Page.php",
            "app/src/PageController.php"
        ]
    },
    "config": {
        "process-timeout": 600
    },
    "prefer-stable": true,
    "minimum-stability": "dev",
    "repositories": {
        "elemental": {
            "type": "vcs",
            "url": "https://github.com/unclecheese/silverstripe-elemental.git"
        },
        "asset-admin": {
            "type": "vcs",
            "url": "https://github.com/unclecheese/silverstripe-asset-admin.git"
        },
        "versioned": {
            "type": "vcs",
            "url": "https://github.com/unclecheese/silverstripe-versioned.git"
        },
        "graphql": {
            "type": "vcs",
            "url": "https://github.com/unclecheese/silverstripe-graphql.git"
        },
        "cms": {
            "type": "vcs",
            "url": "https://github.com/unclecheese/silverstripe-cms.git"
        }
    }
}
```

2020-11-27 04:30 UTC, chillu commented
Tried this on a fresh install, which 

```
composer create-project silverstripe/installer test 4.x-dev
cd test
composer require --no-update silverstripe/graphql:"dev-pulls/master/resolving-the-mystery as 4.x-dev" silverstripe/cms:"dev-pulls/4/resolving-the-mystery as 4.x-dev" dnadesign/silverstripe-elemental:"dev-pulls/4/resolving-the-mystery as 4.x-dev" silverstripe/versioned:"dev-pulls/1/resolving-the-mystery as 1.x-dev" silverstripe/asset-admin:"dev-pulls/1/resolving-the-mystery as 1.x-dev"
composer config repositories.graphql vcs https://github.com/unclecheese/silverstripe-graphql.git
composer config repositories.cms vcs https://github.com/unclecheese/silverstripe-cms.git
composer config repositories.versioned vcs https://github.com/unclecheese/silverstripe-versioned.git
composer config repositories.asset-admin vcs https://github.com/unclecheese/silverstripe-asset-admin.git
composer config repositories.elemental vcs https://github.com/unclecheese/silverstripe-elemental.git
composer update -W
# Required because auto building doesn't seem to work?
vendor/bin/sake dev/graphql/build
```

When going to `admin/assets`, you get a `{"data":{"readFiles":null}}` response.

2020-11-27 04:40 UTC, chillu commented
Filed autobuilding as a separate bug, seems unrelated to the PR: https://github.com/silverstripe/silverstripe-graphql/issues/331

2020-12-01 08:25 UTC, unclecheese commented
The above issue was caused by the resolvers getting overwritten in an `array_replace_recursive` call (numeric keys not getting concatenated). 

Replaced with the idiosyncratic `mergeArray()` function from silverstripe/config.

I have also deleted almost all of the tests. They are no longer compliant with the new API, and will be refactored.

Merging based on:

* tests are now green except asset-admin (dependent PR)
* having this merged will expedite the unit testing effort (currently based on this PR)
* Other PRs have been approved
* Pretty low impact as we're pre-alpha 😉

2020-12-01 08:26 UTC, merged