Significant refactor to several annoying inhibitors to stability
silverstripe/silverstripe-graphql pull request #352
Opened 2021-01-26 10:44 UTC by unclecheese

2021-01-28 05:50 UTC, chillu requested changes
Amazing work as usual, thanks for chipping away at this! Definitely a tough one to peer review as a single commit, but I appreciate the effort to create a changelog - that helps a bit ;)

> SchemaModelInterface now must declare getPropertyForField (gql field -> object property mapping)
> SchemaModelInterface now must declare getSchemaContext and getModelConfiguration

I don't understand this layer enough to determine if that's a good change. Might need to write a bit of an architecture overview doc to get my head around it.

> BuildState API is gone. Use new SchemaContextProvider in resolvers. Pass SchemaContext
objects to the small number of classes that needed it in their internals.

Yep that's a great change, a lot more explicit and testable.

2021-01-28 05:50 UTC, chillu commented on src/Schema/Services/NestedInputBuilder.php
> +class NestedInputBuilder
Needs a description of the class purpose

2021-01-28 05:50 UTC, chillu commented on src/Schema/Services/NestedInputBuilder.php
> +                // Prevent stupid recursion in self-referential relationships, e.g. Parent
Seems like a good candidate for a test?

2021-01-28 05:50 UTC, chillu commented on tests/Schema/Services/NestedInputBuilderTest.php
> +    public function testNestedInputBuilder()
Awesome to see the test setup being so self explanatory

2021-01-28 05:50 UTC, chillu commented on _config/events.yml
> +          on: [ graphqlSchemaBuild ]
This is technically only required for Apollo usage in the CMS, right? Can we limit this to the `admin` schema by default? I'm assuming there either are other GraphQL clients who ignore the type ambiguity, or simpler schemas where that ambiguity is not an issue?

2021-01-28 05:50 UTC, chillu commented on src/Schema/DataObject/Plugin/QuerySort.php
> +        $builder->setFieldFilter(function (Type $type, Field $field) {
Wouldn't this need to be serialised out to generated PHP? I don't understand how this works :D

2021-01-28 05:50 UTC, chillu commented on src/Schema/Schema.php
> +        $this->processTypes();
Given this is a build-time step, where performance is (somewhat) less important than during query execution: What is the purpose of this lazy mechanism? It feels like it's adding another layer of complexity, where you have to assume inconsistent types which need processing before the schema can be persisted?

2021-01-28 05:50 UTC, chillu commented on src/Schema/SchemaContext.php
> +     * @param array $typeMapping
Can you define which type the array should contain? Same with `setFieldMapping()` below.

2021-01-28 05:50 UTC, chillu commented on src/Schema/Storage/templates/type.inc.php
> +                        'resolve' => $resolverInst->toClosure(),
Does this introduce new limits about how resolvers can be defined? I guess they were always static, so there's really no opportunity to close over values that can't be expressed in PHP code?

2021-01-28 05:53 UTC, chillu commented
> Remove IntrospectionProvider extension. Static only. Leaving it to the user to decide never made any sense, and it just slowed down the UI in the CMS. Now that we're doing code gen, it seems like the static solution is more consistent.

How will that work when the schema build is performed outside of the production environment, e.g. during CI when creating a deployment package? That environment won't have access to the production `assets/` folder.

2021-02-02 22:11 UTC, unclecheese commented on src/Controller.php
> +        if ($schema) {
Yup, there's no reason Schema should be passed around at query time. That's why the context provider is just giving you the `SchemaContext` object. That class is designed to encapsulate only that schema state that might be relevant to you in resolvers.

I don't know why it takes Schema as its constructor. Maybe the idea is that `provideContext` could at some point provide more keys, like:

```php
    public function provideContext(): array
    {
        return [
            self::KEY => $this->schema->getStore()->getContext(),
            'types' => array_keys($this->schema->getTypes())
        ];
    }
```

But as far as I can tell, this should be constructed with a SchemaContext object.

2021-02-02 22:16 UTC, unclecheese commented on _config/events.yml
> +          on: [ graphqlSchemaBuild ]
Checked in on this. Apollo needs it when you have fragments that are pinned to ambiguous types (Unions and Interfaces). We do that in asset-admin.

We could just forget the whole thing if we ditched the fragments and duplicated some code, or we could just press forward and make this work only on admin.

Easiest thing is to just pin it to the admin schema using the event dispatcher's inbuilt dot syntax:

```
   properties:
      handlers:
        graphqlTranscribe:
          on: [ graphqlSchemaBuild.admin ]
```

2021-02-02 22:22 UTC, unclecheese commented on src/Schema/DataObject/Plugin/QuerySort.php
> +        $builder->setFieldFilter(function (Type $type, Field $field) {
The way these classes are named makes this very hard to understand. Basically there are three kinds of these query plugins:

* Something super opinionated that you apply to a model operation (MyObject read: true)
* Something more flexible that you can apply to a custom query that returns dataobjects
* Something very generic that leaves you to do all the wiring (e.g. just adds the input types to the schema, and adds an argument)

We need to embrace better naming conventions for all these cases. Right now, the space is very overloaded with generic terminology.

But in this case, this is basically #2 on the list asserting that in addition to what #3 does, it only works on fields that are model-backed.

This is a bit messy ATM, and there's a hackday PR in the future. :)

2021-02-02 22:37 UTC, unclecheese commented on src/Schema/Schema.php
> +        $this->processTypes();
It ensures that plugins are always dealing with a schema state that is as close to the original as possible, so minimise the impact of order of execution in the plugin list.

Because plugins have the ability to mutate the schema, you can have things like `query->setType()` to some new thing (e.g. pagination), and that can obfuscate important information to a plugin.

I wish I could think of the example now, but I think it was pagination, where you had a query like `readPages` returning type `SilverStripe\CMS\Model\SiteTree`.

2021-02-02 22:46 UTC, unclecheese commented on src/Controller.php
> +        $handler->addContextProvider(UserContextProvider::create($user))
> Also, any middleware is receiving $context as an array. Do we need a ContextProvider::set($myArray, $myValue) equivalent so that middleware and resolvers can deal with the same level of abstraction here?

If a middleware wants to mutate context, it should create a ContextProvider to go with it that contains internals for get and set. The idea is to get away from having to guess what the name of the key is. Classes are easier to discover than strings. :-)


> That's a pretty roundabout way to wrap a strongly typed API around a weakly typed one inherited by the library.

I think, as we discussed earlier, modules make a good case for doing it this way, e.g. fluent / subsites, which might want to provide context in some kind of middleware layer.

2021-02-02 23:57 UTC, unclecheese commented on src/Schema/Services/NestedInputBuilder.php
> +                // Prevent stupid recursion in self-referential relationships, e.g. Parent
It actually is tested. `FakeProduct` has a self-referential relation to `relatedProducts`. If this functionality didn't work, the `assertSchema` test would fail because there would be more inputs.

2021-02-02 23:58 UTC, unclecheese commented on src/Schema/Storage/templates/type.inc.php
> +                        'resolve' => $resolverInst->toClosure(),
Seems unlikely. `CompsedResolver` should never be used externally.

2021-02-02 23:59 UTC, unclecheese commented on src/Schema/Storage/templates/type.inc.php
> +                        'resolve' => $resolverInst->toClosure(),
Actually, I think we need to validate that the callables are not instance of Closure. Good call.

2021-02-03 01:03 UTC, unclecheese commented
> How will that work when the schema build is performed outside of the production environment, e.g. during CI when creating a deployment package? That environment won't have access to the production assets/ folder.

OK, now:

* Remove `GeneratedAssetHandler` dependency from `SchemaTranscriber` (injector hell for one little file)
* `admin` module adds event for `graphqlSchemaBuild.admin` (only applies to admin schema)
* `SchemaTranscriber` has new `rootDir` property that defaults to `PUBLIC_PATH`
* Graphql special `assets.yml` config (behind moduleexists) sets `rootDir` of `SchemaTranscriber` from `PUBLIC_PATH` to `ASSETS_PATH`
* Document edge case for running SS without assets installed -- block those `.graphql` files to outside traffic

2021-02-03 04:29 UTC, unclecheese commented on src/Schema/DataObject/FieldAccessor.php
> +    public function hasNativeField(
We now have full test coverage on `FieldAccessor`! Easy win.

2021-02-04 04:43 UTC, chillu commented
I've sent a (very straightforward) devtools PR for this: https://github.com/silverstripe/silverstripe-graphql-devtools/pull/33

2021-02-04 05:09 UTC, chillu commented on src/Controller.php
> +        if ($schema) {
Sweet, I've done this in 3dfcca7e778cd23f04058d0bcdc1cdee260e61cc

2021-02-04 20:25 UTC, chillu commented
Also fixed frameworktest with https://github.com/silverstripe/silverstripe-frameworktest/pull/84

2021-02-04 20:26 UTC, chillu commented on src/Controller.php
> +        if ($schema) {
OK that's done now in https://github.com/silverstripe/silverstripe-graphql/pull/352/commits/3dfcca7e778cd23f04058d0bcdc1cdee260e61cc

2021-02-04 22:19 UTC, chillu commented on src/Controller.php
> +        $handler->addContextProvider(UserContextProvider::create($user))
Yeah modules with their own context providers validate that level of composition. I've documented that through https://github.com/unclecheese/silverstripe-framework/commit/1be5f471de7bce661f1db18c78bbcf9371dfefa5

2021-02-14 22:00 UTC, unclecheese commented
Test failure is due to the `silverstripe/versioned` dependency.

2021-02-15 05:57 UTC, chillu requested changes
Refactoring the `StorableSchema` as a value object is great, much cleaner. I'm still a bit confused why we need a `Schema` that's *separate* from a `SchemaBuilder` during the build phase. Feels like this could be inlined into `SchemaBuilder` to avoid confusion between the two "schema" types which perform very different objectives. But I don't think it's worth extra effort at this point, you describe the responsibilities pretty clearly in PHPDoc - and we've already identified the need for an architecture overview doc.

> How will that work when the schema build is performed outside of the production environment, e.g. during CI when creating a deployment package? That environment won't have access to the production assets/ folder.

I don't think your explanation covers it. The "run cms without assets module" edge case is worth covering, but I'm more concerned about building the schema during CI. If this `<schema>.types.graphql` file is created *anywhere other than* `PUBLIC_PATH`, it simply won't be accessible by the browser. You removed the dynamic fallback which is fine in general (since creation is part of a build that's a necessary precondition anyway). But you also removed the dynamic passthrough of a file's contents when they don't live in `PUBLIC_PATH`.

That's important to resolve, because it means that CI-based builds would break `admin/assets`. The schema cache files exist on the webserver(s) because they're part of the production deployment. The types file doesn't, because it's either stuck in CI on `PUBLIC_PATH` (which will get filtered out of the deployment artefact), or because it's in a path where the webserver can't directly serve it without going through `file_get_contents()`.

2021-02-15 05:57 UTC, chillu commented on src/Schema/SchemaBuilder.php
> +    public function read(string $key): ?SchemaContext
This feels like a poor naming choice: `read()` returns `SchemaContext`, `fetch()` returns `GraphQLSchema`. How about `getContext()` and `getSchema()`? Using "fetch" rather than "get" feels a bit arbitrary, especially since it deviates from the "inner" methods in `getStoreCreator()`

2021-02-15 05:57 UTC, chillu commented on src/Schema/SchemaContext.php
> +        $model = $this->createModel($class);
Getters with side effects? Shouldn't that be an explicit decision by the caller? The `createModel` call creates a cache entry, and the creator gets a reference to this context (`$creator->createModel($class, $this)`) - so execution order might matter here. Could be that the opaqueness is a feature here, just checking.

2021-02-15 05:59 UTC, chillu commented on src/Schema/Schema.php
> +        $this->processTypes();
Not sure I'm following, but I trust your judgement on this :) Thanks for taking the time to explain!

2021-02-15 20:54 UTC, chillu commented
Just noted the overlap with https://github.com/silverstripe/silverstripe-framework/issues/9688 - by merging this PR we're making a stronger (not yet semver binding) commitment to supporting `silverstripe/event-dispatcher`

2021-02-16 03:07 UTC, unclecheese commented on src/Schema/SchemaBuilder.php
> +    public function read(string $key): ?SchemaContext
Yeah this gets a bit tricky. So the intention here is to make it clear to the user what they can do. In resolvers interacting with the schema, you're performing readonly operations. 

Latest commit uses `getConfig(string $key): SchemaConfig` 👍

`getSchema()` is ambiguous, because `boot` returns a Schema object, but I think we can live with that.

2021-02-16 08:44 UTC, unclecheese commented on tests/Schema/SchemaBuilderTest.php
> +                        'graphqlSchemaBuild' => [
These identifiers are actually arbitrary. 🤷‍♂️

2021-02-17 02:15 UTC, chillu commented on src/Schema/StorableSchema.php
> +        $queryType = $this->types[Schema::QUERY_TYPE] ?? null;
Technically you could have a schema with *just* mutations, right?

2021-02-17 02:21 UTC, chillu commented on src/Schema/SchemaContext.php
> +        $model = $this->createModel($class);
Aaron has refactored this now

2021-02-17 02:36 UTC, unclecheese commented on src/Schema/StorableSchema.php
> +        $queryType = $this->types[Schema::QUERY_TYPE] ?? null;
Nope. Believe it or not, at least one query is required.

2021-02-17 02:39 UTC, unclecheese commented on src/Schema/StorableSchema.php
> +        $queryType = $this->types[Schema::QUERY_TYPE] ?? null;
Actually, i _think_ the reason for this is for the IDE. It works based on `query {  __schema }` which can't exist if there's no query type, and you can't just leave an empty query type in there with no fields, either. So `query` is implicitly required.

2021-02-17 03:11 UTC, chillu approved these changes

2021-02-17 03:14 UTC, merged