FIX: input building in cyclic graps
silverstripe/silverstripe-graphql pull request #371
Opened 2021-03-01 10:07 UTC by mleutenegger

This PR aims to fix a bug in the `NestedInputBuilder` where a cyclic graph prohibits the building of all necessary nested types on filter and sort input-types.

2021-03-01 21:33 UTC, unclecheese requested changes
Looks good. Just some tidy up and a new API call I would recommend using.

2021-03-01 21:33 UTC, unclecheese commented on src/Schema/Services/NestedInputBuilder.php
>          $level++;
If we're getting rid of `max_nesting`, I think we can do away with this parameter
```suggestion

```

2021-03-01 21:33 UTC, unclecheese commented on src/Schema/Services/NestedInputBuilder.php
> +                // if ($level > $this->config()->get('max_nesting')) {
Is it the conclusion from this issue that the edge cases around `max_nesting` make implementation too problematic to support? I'm fine with that. It's mostly a build performance optimisation.

2021-03-01 21:33 UTC, unclecheese commented on src/Schema/Services/NestedInputBuilder.php
> +                } elseif (isset($seenConnections[$type->getName()][$fieldObj->getName()])) {
Let's use the new `Schema::getState()` API for this. There are too many cases in plugins where you need to track state across a build, which is why I added this recently.

```php
$seen = $this->schema->getState()->get([
  static::class,
  'seenConnections',
  $type->getName(),
  $fieldObj->getName()
]);
```

2021-03-01 21:33 UTC, unclecheese commented on src/Schema/Services/NestedInputBuilder.php
> +                    $seenConnections[$type->getName()][$fieldObj->getName()] = true;
```suggestion
$this->schema->getState()->set([
  static::class,
  'seenConnections',
  $type->getName(),
  $fieldObj->getName()
], true);

2021-03-01 21:33 UTC, unclecheese commented on src/Schema/Services/NestedInputBuilder.php
> +    protected function buildAllFieldsConfig(Type $type, int $level = 0, array &$seenConnections = []): array
```suggestion
    protected function buildAllFieldsConfig(Type $type): array
```

2021-03-01 21:33 UTC, unclecheese commented on src/Schema/Services/NestedInputBuilder.php
> +                    $map[$fieldObj->getName()] = $this->buildAllFieldsConfig($nestedType, $level, $seenConnections);
```suggestion
                    $map[$fieldObj->getName()] = $this->buildAllFieldsConfig($nestedType);
```

2021-03-01 21:33 UTC, unclecheese commented on src/Schema/Services/NestedInputBuilder.php
> +                // if ($level > $this->config()->get('max_nesting')) {
If so, let's remember to remove the config setting and update any documentation that points to it.

2021-03-01 21:40 UTC, mleutenegger commented on src/Schema/Services/NestedInputBuilder.php
> +                // if ($level > $this->config()->get('max_nesting')) {
:+1: I'd even argue that using a solution which terminates on known edges is faster. Not going to do the math though, as its a prebuild step and really not impacting performance of the application.

2021-03-03 02:36 UTC, unclecheese approved these changes
Beautiful. Excellent work!

2021-03-03 02:36 UTC, merged