NEW: DBField arguments, Enum, Composite support
silverstripe/silverstripe-graphql pull request #398
Opened 2021-07-29 02:52 UTC by unclecheese

This pull request adds three new plugins to better support `DBField` types

### DBFieldArgsPlugin

* Adds a new `format` argument to DBField types that have formatting methods, e.g. `FirstParagraph`.  (`content(format: FIRST_PARAGRAPH) )`
* When appropriate, a `limit` argument is added, e.g. `content(format: LIMIT_SENTENCES, limit: 5)`
* New `format` argument for date / time fields, e.g. `lastEdited(format: DAY_OF_WEEK)`
* All up, there are nine of these adapters (Text, Decimal, and Date ancestries)

### DBFieldTypes plugin

* `DBEnum` creates a proper `Enum` type in the schema, and gets assigned to the field
* Composite fields, e.g. `DBFile` create proper object types in the schema and get assigned to the field

### ScalarDBField plugin

* Ensure DBFields are always returned as scalars (no longer done in the default DataObject resolver. see below)

## New low-level stuff

* **Default DataObject resolver no longer normalises to scalars**: The above changes required changing the default DataObject resolver to no longer return `$dbField->getValue()` (scalar) and rather leave the instance in tact so the other resolvers  could act upon it (e.g. $obj->FirstParagraph()). There is now a plugin that runs at the end of the resolver stack that ensures if the object is DBField, it will run `->forTemplate()` on it to extract its scalar value

* `ModelField` now accepts a `metadata` property. This may be a bit overkill, but we needed a place to store state on how the field was created, e.g. from introspection of a DBField. (`->getMetadata()->get('dataClass')`). As yet there are no other uses for this storage, but it's conceivable that other plugins or future features will want to add arbitrary state to fields.

* Schema config now has a `parseShortcodes` property as a global setting for `DBHTMLText` fields. (false in admin, true in default). This can also be set per field in `myHTMLField(parseShortcodes: false)`

## Todo:
* Docs
* Tests

## Relevant, but not necessarily dependent

* https://github.com/silverstripe/silverstripe-admin/pull/1242 (adds shortcodes: false... won't break anything if merged ahead)

2021-07-31 02:58 UTC, unclecheese commented
Failed build is due to a branch pushed to origin that was later deleted.

2021-08-24 06:02 UTC, emteknetnz requested changes
Looking good

I'm don't have enough context to really challenge the approach taken here, so I'll just assume it's a great idea :-)

Allowing php formatting to be specified via a graphql quer is certainly interesting.  It does seem slightly wrong since usually that's supposed to happen client side, though I personally think it's a good convenience and it faciliates code reuse.

I've left some comments around some opportunities to tidy up the code

2021-09-02 21:38 UTC, unclecheese commented on src/Schema/Field/ModelField.php
> +    public function getMetadata(): Configuration
`Configuration` is a basic utility class that acts as a value object with some nice dev features, like `get('someCategory.nested.propertyName', 'defaultValue')`. It's used in several corners of the codebase.

2021-09-02 21:40 UTC, unclecheese commented on src/Schema/DataObject/Resolver.php
> +        while (!$resolvedField && $class !== DataObject::class) {
Only if the resolver was not used on a DataObject, but yeah, good catch. Have added an extra check.

2021-09-02 21:42 UTC, unclecheese commented on src/Schema/DataObject/Plugin/ScalarDBField.php
> +            if ($field instanceof ModelField && $field->getModel() instanceof DataObjectModel) {
Lol, I love early exits, and I think I had it that way at first, but realised it was more lines of code to do it. But happy to put it back.

2021-09-02 21:43 UTC, unclecheese commented on src/Schema/DataObject/Plugin/ScalarDBField.php
> +    const IDENTIFIER = 'scalarDBField';
I'm going to hold off on this one simply because we have constants all over the place in this module and none of them use visibility, and I'd rather keep the consistency. Adding visibility sounds like a great follow-up PR, however.

2021-09-02 21:46 UTC, unclecheese commented on src/Schema/DataObject/Plugin/DBFieldArgs/DBDatetimeArgs.php
> +                'DATE' => 'Date',
To what end? And how would you go about merging with the parent?

2021-09-02 21:48 UTC, unclecheese commented on src/Schema/DataObject/Plugin/DBFieldArgs/DBDecimalArgs.php
> +            'INT' => 'Int',
These all map to methods that are available on the DBField instance. I don't see a `Decimal()` method on `DBDecimal`. Just `Int()` and `Nice()`. (Nice() changes the type to a string, so we can't do it)

2021-09-02 21:51 UTC, unclecheese commented on src/Schema/DataObject/Plugin/DBFieldArgs/DBDateArgs.php
> +        return [static::class, 'resolve'];
Yeah, I definitely see why it might make sense, but I'm not crazy about these duck typing approaches. We have enough of it in the resolver discovery pattern. I really prefer the expressivity of having as much information as possible in the class definition itself rather than having to find out there's some implicit magic happening upstream.

2021-09-02 21:55 UTC, unclecheese commented on src/Schema/DataObject/DataObjectModel.php
> +    private function applyMetadata(ModelField $field, ?string $class = null): ModelField
It's a private function, so we can always refactor it, but originally it seemed like there might be more metadata the model would want to stamp on the field. I've since realised the other metadata isn't necessary, and it is now just the DBField class. If we do someday discover that we need more metadata, it's now just a one-liner to that function rather than updating all the methods that invoke it now needing to call multiple methods.


Fair point on the return type. Fluent setters don't make a whole lot of sense in private methods.

2021-09-02 21:57 UTC, unclecheese commented on src/Schema/DataObject/DataObjectModel.php
> +    private function applyMetadata(ModelField $field, ?string $class = null): ModelField
Ah, I see what you mean now. The argument signature of `applyMetadata` just accepts a `$class`. Yeah, we should update that method name. 👍

2021-09-06 02:27 UTC, emteknetnz approved these changes

2021-09-06 02:28 UTC, merged