NEW: custom filter fields
silverstripe/silverstripe-graphql pull request #431
Opened 2022-01-06 22:26 UTC by unclecheese

Resolves https://github.com/silverstripe/silverstripe-graphql/issues/406

2022-01-06 23:04 UTC, unclecheese commented
Docs: https://github.com/silverstripe/silverstripe-framework/pull/10192

2022-01-20 01:53 UTC, emteknetnz commented on src/Schema/Services/NestedInputBuilder.php
> +    public function __construct(Field $root, Schema $schema, $fields = Schema::ALL, $resolveConfig = [])
Add param types e.g. `array $resolveConfig = []`

2022-01-20 01:56 UTC, emteknetnz requested changes
Looks good

Couple of very minor things

2022-01-20 01:56 UTC, emteknetnz commented on src/Schema/Storage/CodeGenerationStore.php
> +     * If true, s
Looks like this is missing some text

2022-01-20 01:56 UTC, emteknetnz commented on src/Schema/Services/NestedInputBuilder.php
> +    public function __construct(Field $root, Schema $schema, $fields = Schema::ALL, $resolveConfig = [])
Add param types e.g. `array $resolveConfig = []`

2022-01-20 06:38 UTC, merged