WIP: Bulk loader
silverstripe/silverstripe-graphql pull request #432
Opened 2022-01-10 23:46 UTC by unclecheese

```
elemental: # arbitrary key to define what this set of loaders is doing
  load:
    inheritanceLoader:
      include:
        - DNADesign\Elemental\Models\BaseElement
  apply:
    fields:
      '*': true
    operations:
      read: true
      readOne: true
app:
  load:
    namespaceLoader:
      include:
        - 'App\Models\*'
      exclude:
        - 'App\Models\Secret\*'
  apply:
    fields:
      '*': true
    operations:
      '*': true
```

2022-01-11 10:18 UTC, kinglozzer commented on src/Schema/BulkLoader/CollectionFactory.php
> +        $loader = require(BASE_PATH . '/vendor/autoload.php');
I think this will only work for valid PSR-4 classes, or classes manually loaded in composer.json? Annoyingly we still have our own class loader that picks up classes anywhere :/

https://github.com/silverstripe/silverstripe-framework/blob/8a73a4ad22c993e5fef99a6e8e96854437f68345/src/Core/Manifest/ClassLoader.php#L76-L79

2022-01-11 19:46 UTC, unclecheese commented on src/Schema/BulkLoader/CollectionFactory.php
> +        $loader = require(BASE_PATH . '/vendor/autoload.php');
Yeah, found that out the hard way. There are several classes it can't find. The only reason we need this is to get the file path for classes, so we can do a `filesystemLoader`, e.g. `include: [src/Models/*]`.

Wondering:

* Is that something we even want?
* Is there an alternative way to get a filename for a class?

2022-01-12 04:33 UTC, michalkleiner commented on src/Schema/BulkLoader/CollectionFactory.php
> +        $loader = require(BASE_PATH . '/vendor/autoload.php');
@unclecheese https://www.php.net/manual/en/reflectionclass.getfilename.php

2022-01-12 09:17 UTC, kinglozzer commented on src/Schema/BulkLoader/CollectionFactory.php
> +        $loader = require(BASE_PATH . '/vendor/autoload.php');
I’m not sure, I think we probably _do_ want that because I know some devs don’t namespace their app code at all - presumably a path-based `include:` would be the only way to bulk load those classes?

Reflection is an option. Alternatively we could grab the `ClassLoader` from `CoreKernel`, from there get a list of `ClassManifest` instances (I think there’s typically only ever one instance?) and then use [`ClassManifest::getItemPath($class)`](https://github.com/silverstripe/silverstripe-framework/blob/8a73a4ad22c993e5fef99a6e8e96854437f68345/src/Core/Manifest/ClassManifest.php#L333-L346).

If this is only called during schema build, Reflection is probably the better option - a slight performance hit is acceptable during builds

2022-01-12 19:09 UTC, unclecheese commented on src/Schema/BulkLoader/CollectionFactory.php
> +        $loader = require(BASE_PATH . '/vendor/autoload.php');
Yeah I ended up finding the relflection option yesterday and went with that approach in the new `filepathLoader` option. Thanks!

2022-01-20 02:25 UTC, emteknetnz requested changes
Looks good, some very minor things

2022-01-20 02:25 UTC, emteknetnz commented on src/Schema/BulkLoader/AbstractBulkLoader.php
> +
Remove extra blank line

2022-01-20 02:25 UTC, emteknetnz commented on src/Schema/BulkLoader/AbstractBulkLoader.php
> + * Provides base functionality to all bulk loaders. Must define a collect() method.
`Must define a collect() method.` - This is a bit confusing since there's collect is a `public function` while we also have `abstract public static function getIdentifier(): string;` which does actually need to be defined

2022-01-20 02:25 UTC, emteknetnz commented on src/Schema/BulkLoader/BulkLoaderSet.php
> +
Remove extra blank line

2022-01-20 02:25 UTC, emteknetnz commented on src/Schema/BulkLoader/BulkLoaderSet.php
> +    public function setLoaders($loaders): self
$loaders should have a type of array?

2022-01-20 02:25 UTC, emteknetnz commented on src/Schema/BulkLoader/ExtensionLoader.php
> +
Remove extra blank line

2022-01-20 02:25 UTC, emteknetnz commented on src/Schema/BulkLoader/FilepathLoader.php
> +
Remove extra blank line

2022-01-20 02:25 UTC, emteknetnz commented on src/Schema/BulkLoader/InheritanceLoader.php
> +
Remove extra blank line

(and do same on all subsequent files)

2022-01-20 02:25 UTC, emteknetnz commented on src/Schema/BulkLoader/ExtensionLoader.php
> +    const IDENTIFIER = 'extensionLoader';
```suggestion
    public const IDENTIFIER = 'extensionLoader';
```
Also update it for all subsequent IDENTIFIER's in following files

2022-01-20 02:25 UTC, emteknetnz commented on src/Schema/BulkLoader/ExtensionLoader.php
> +    public function exclude(array $exclude): AbstractBulkLoader
add docblock to be consistent with other methods

2022-01-20 02:25 UTC, emteknetnz commented on src/Schema/Interfaces/Identifiable.php
> + * Used by any class that delcares an identifier
```suggestion
 * Used by any class that declares an identifier
```

2022-01-20 03:36 UTC, michalkleiner commented on src/Schema/Interfaces/Identifiable.php
> +interface Identifiable
I generally support using interfaces, but the name here and that it's used to populate the registry of available loaders is a bit misleading in my opinion. Can we achieve the same looking for subclasses of `AbstractBulkLoader`?

2022-01-20 04:08 UTC, unclecheese commented on src/Schema/Interfaces/Identifiable.php
> +interface Identifiable
The idea is that this could someday become reusable. We're using this pattern more and more where we just have a holding tank for a given set of implementations. At a bare minimum, a registry should be able to find implementations by an identifier. In practise, it should be a thing with an identifier that also implements or inherits from a given contract, e.g. `AbstractBulkLoader` or `ModelQueryPlugin`.. I have yet to figure that last part out. 

But what I'm trying to avoid is lighting up a new concretion for every single registry use case we have -- BulkLoaders, Plugins, etc... seems like a good case for abstraction.

2022-01-20 04:11 UTC, unclecheese commented on src/Schema/BulkLoader/AbstractBulkLoader.php
> + * Provides base functionality to all bulk loaders. Must define a collect() method.
Yeah, used to be abstract and now it's basically a noop. Have updated.

2022-01-20 10:08 UTC, merged