NEW: Schema initialise task
silverstripe/silverstripe-graphql pull request #433
Opened 2022-01-17 19:34 UTC by unclecheese

There's too much boilerplate in setting up a default schema. What this does:

2022-01-20 01:44 UTC, emteknetnz requested changes
Concept seems OK?  Feels like it needs more work around CLI documentation and experience

2022-01-20 01:44 UTC, emteknetnz commented on src/Dev/Initialise.php
> +
Remove this blank line, it'll fail PHPCS

2022-01-20 01:44 UTC, emteknetnz commented on src/Dev/Initialise.php
> +
May as well remove this blank line too

2022-01-20 01:44 UTC, emteknetnz commented on src/Dev/Initialise.php
> +        $schemaName = $request->getVar('name');
You need to put docs for CLI arguments somewhere more accessible to end-users i.e. not the PR description.

2022-01-20 01:44 UTC, emteknetnz commented on src/Dev/Initialise.php
> +            echo "Config file $absConfigFile already exists. Skipping." . PHP_EOL;
Would it be better to suffix the config if the graphql.yml file already exists?

2022-01-20 01:44 UTC, emteknetnz commented on src/Dev/Initialise.php
> +        foreach (['models', 'config', 'types', 'queries', 'mutations'] as $file) {
indentation in this method is all over the place

2022-01-20 01:44 UTC, emteknetnz commented on src/Dev/Initialise.php
> +            touch(Path::join($absGraphQLDir, "$file.yml"));
I don't think creating a bunch of empty files adds much value.  I think it's fine having only the config.yml file here.

2022-01-20 01:44 UTC, emteknetnz commented on src/Dev/Initialise.php
> +    private $perms = '0777';
I think values like this and $projectDir, which will get dynamically set during the `initialise()` method, are better off being left as blank strings. It's confusing having '0777' whens it's never used as it just get changed straight away

2022-01-20 01:44 UTC, emteknetnz commented on src/Dev/Initialise.php
> + * @package SilverStripe\GraphQL\Dev
Do we even need this Class / @package docblock anymore?  I can't image there's any IDE's out that there can't figure this out based on the actual namespace and the class name

2022-01-20 01:44 UTC, emteknetnz commented on src/Dev/Initialise.php
> +
Remove blank line

2022-01-20 01:44 UTC, emteknetnz commented on src/Dev/Initialise.php
> +
Remove blank line

2022-01-20 01:44 UTC, emteknetnz commented on src/Dev/Initialise.php
> +            'Please provide a base namespace for your app, e.g. "namespace=App" or "namespace=MyVendor\MyProject"'
extremely ugly user experience

```
www-data@www:/var/www$ vendor/bin/sake dev/graphql/init 
ERROR [Emergency]: Uncaught SilverStripe\GraphQL\Schema\Exception\SchemaBuilderException: Please provide a base namespace for your app, e.g. "namespace=App" or "namespace=MyVendor\MyProject"
IN GET dev/graphql/init
Line 1226 in /var/www/vendor/silverstripe/graphql/src/Schema/Schema.php                                                                                                             

Source
======
  1217:     * @param $test
  1218:     * @param string $message
  1219:     * @param mixed ...$params
  1220:     * @throws SchemaBuilderException
  1221:     */
  1222:    public static function invariant($test, $message = '', ...$params): void
  1223:    {
  1224:        if (!$test) {
  1225:            $message = count($params) > 0 ? sprintf($message, ...$params) : $message;
* 1226:            throw new SchemaBuilderException($message);
  1227:        }
  1228:    }
  1229:}

Trace
=====
SilverStripe\GraphQL\Schema\Schema::invariant(, Please provide a base namespace for your app, e.g. "namespace=App" or "namespace=MyVendor\MyProject")
Initialise.php:93

SilverStripe\GraphQL\Dev\Initialise->initialise(SilverStripe\Control\HTTPRequest)
RequestHandler.php:323

SilverStripe\Control\RequestHandler->handleAction(SilverStripe\Control\HTTPRequest, initialise)
Controller.php:286
```

(very long strack trace follows)

2022-01-20 01:44 UTC, emteknetnz commented on _config/dev.yml
> +    init:
Is there any docs that links to `vendor/bin/sake dev/graphql/init`?  Right now it's very hidden

2022-01-20 01:44 UTC, emteknetnz commented on src/Dev/Initialise.php
> + * More information: https://docs.silverstripe.org/en/4/developer_guides/graphql/working_with_generic_types/resolver_discovery/#the-resolver-discovery-pattern
Lines too long, will fail PHPCS

2022-01-20 01:44 UTC, emteknetnz commented on src/Dev/Initialise.php
> +    public static function resolveMyQuery(\$obj, array \$args, \$context): array
$context has no type - shouldn't it have something defined?

2022-01-20 01:44 UTC, emteknetnz commented on src/Dev/Initialise.php
> +YAML;
Needs a blank line at end of file

2022-01-27 22:01 UTC, unclecheese commented on src/Dev/Initialise.php
> +        $schemaName = $request->getVar('name');
Have added a `help` option

2022-01-27 22:09 UTC, unclecheese commented on src/Dev/Initialise.php
> +            echo "Config file $absConfigFile already exists. Skipping." . PHP_EOL;
Ideally, this would do a similar check that the GraphQL devtools controller does, where it finds what schemas are actually routed. That's in a separate module, and it's got some GraphQL 3 backward compat stuff in it.

I'm thinking that if you have a `graphql.yml` file, you're past the point of needing this tool? I'd rather be paranoid of clobbering someone's existing config.

2022-01-27 22:12 UTC, unclecheese commented on src/Dev/Initialise.php
> +            touch(Path::join($absGraphQLDir, "$file.yml"));
I actually think it does. There's a lot of naming conventions to learn in GraphQL 4, and this just saves a trip to the docs. At a bare minimum, we need `config.yml` and `models.yml`, but really, I'd prefer to just do empty files. You're going to need them at some point, and for users who don't know about custom types/queries, it creates a nice footprint that shows you a bit of what the module can do without forcing you down the documentation path.

2022-01-27 22:13 UTC, unclecheese commented on src/Dev/Initialise.php
> +    private $perms = '0777';
Yup, fair enough.

2022-01-27 22:18 UTC, unclecheese commented on src/Dev/Initialise.php
> +            'Please provide a base namespace for your app, e.g. "namespace=App" or "namespace=MyVendor\MyProject"'
Changed to standard output.

2022-01-27 22:19 UTC, unclecheese commented on src/Dev/Initialise.php
> +    public static function resolveMyQuery(\$obj, array \$args, \$context): array
Yeah, good point. I think it's always an array? Hope it's not nullable. :)

2022-01-28 00:50 UTC, unclecheese commented on src/Dev/Initialise.php
> + * More information: https://docs.silverstripe.org/en/4/developer_guides/graphql/working_with_generic_types/resolver_discovery/#the-resolver-discovery-pattern
The link itself is enough to break the limit. What would you recommend?

2022-01-28 00:50 UTC, unclecheese commented
Docs are here: https://github.com/silverstripe/silverstripe-framework/pull/10218

2022-02-08 09:08 UTC, unclecheese commented on _config/dev.yml
> +    init:
https://github.com/silverstripe/silverstripe-framework/pull/10218

2022-02-08 09:09 UTC, unclecheese commented
Revisions made per feedback.

2022-02-08 10:40 UTC, michalkleiner commented on src/Dev/Initialise.php
> +            touch(Path::join($absGraphQLDir, "$file.yml"));
Having worked with GQL4 I tend to agree that any help in code/prebaked configs is closer to the hands-on dev and therefore better than having to go and read docs to then do the same thing anyway. Even from the perspective of naming the files and what they may contain.

2022-04-26 02:28 UTC, GuySartorelli commented on src/Dev/Initialise.php
> +            echo "Config file $absConfigFile already exists. Skipping." . PHP_EOL;
I think this is a good way of handling it - if the file already exists, we inform the developer of that fact and skip it. They can then make a judgement call to either keep the existing schema definition or delete it and run this again.

2022-05-23 04:20 UTC, maxime-rainville commented
I'm wondering if maybe we want to move this to the GraphQL dev tools module instead? That way we can just call it experimental and merge it.

2022-05-23 04:23 UTC, GuySartorelli commented
I don't necessarily think that we should push it off to another module just to get it merged if it's something that we think _should_ be in core at the end of the day... that said, this _is_ ultimately something that helps at dev-time and shouldn't be used in a production environment (if I understand it correctly) so dev tools does genuinely seem to be a better place for it.

2022-05-23 04:44 UTC, unclecheese commented
I don't see it as a good fit for dev tools. I'll try to explain why.

There are essentially two use cases for this module:

* Make the CMS work
* Provide a bespoke GraphQL schema for my app

In the case of the latter, your entry point is now creating a bunch of boilerplate yaml before you can request a single byte of data. The time when this feature is most useful is during that time. Your journey will be going to the docs, getting the tl;dr on how you do it, and if we can deliver a single CLI task to get you into your schema in a few minutes rather than hours, we should not pass on the opportunity to provide that value. With devtools, b the time you've got your hands dirty and are seeking the features of that module, it's too late for this to be effective. 

You could certainly make the case that if you're building a bespoke GraphQL server in Silverstripe CMS, you're highly unlikely to do it without the devtools module (imagine building a schema and not testing out any queries in the IDE!), and this is just another reinforcement of the criticality of that module when doing a custom GraphQL schema, but I think that speaks more to the case for renaming the devtools module to "silverstripe-graphql-custom-schema" or something -- in other words, a specific module that provides tools to break GraphQL out of the conceptual boundaries of the CMS, rather than framing it as a power-user addon.

I'm more wondering what's left to do on this PR? It's been stale for months, which is fine, but I don't think the fact that its been sitting for a while should be a pretext for changing its intended domain.

2022-05-23 04:55 UTC, GuySartorelli commented
> Your journey will start with the docs or a Slack message to get the tl;dr on how you do it .
> ...
> With devtools, by the time you've got your hands dirty and are seeking the features of that module, it's too late for this to be effective.

This seems to me like it's ultimately a matter of documentation - if the documentation says something along the lines of "An easy way to get started creating your schema is using the schema initialise task in the devtools module" with a link to that module, then it brings not only this functionality but also the dev tools module in general to the attention of people who are just starting out with making their custom graphql schema.

> I'm more wondering what's left to do on this PR? 

There were a few discussion points that someone just needs to make a call on, I think - maybe @emteknetnz could take another look now that his questions have been answered.

> I don't think the fact that its been sitting for a while should be a pretext for changing its intended domain.

Agreed - but now that the question has been asked I think it does behoove us to decide if this code might be better suited to devtools. If the only reason for it not to be there is that we want to make people aware of it, I think that's a matter of documentation as I mentioned above. In general it would be better to keep code intended for use at development time in a module intended to be a dev dependency.

2022-05-23 05:01 UTC, unclecheese commented
The thing is, 90% of the code in this module is _not intended for production_. The whole thing is a giant task that creates an artefact that _is_ intended for production. So shipping dev code is part of the purchase at this point.

Reading a "Quick Start" documentation for a module and getting told that you need to install another module to do the quick start is probably a good indication that we've crippled the DX. I just don't see any positive outcomes from that.

2022-05-24 21:55 UTC, maxime-rainville commented
Yeah ... to me this sounds more like a documentation concern. Having a quick way to scaffold a graphql schema is pointless if you don't also have a quick way to run a dummy query against it. The doc should push you to install the dev tools early.

On a side note, we probably need to start providing more formal support for those dev-tools.

2022-05-24 22:37 UTC, unclecheese commented
In theory, the devtools module shouldn't have to exist. The graphql module is itself, for devs. It produces a single deployable artefact. Really everything but the controller could be left out of the deployment. So it makes sense that the IDE and all of its furnishings should ship with the module.

It was this way for a short time, until we realised that GraphQL Playground came with massive JS bundle that bloated this repository. We decided to prune the commits and move the playground to a separate module. That minor detail is what put us on this path of two separate modules, and it's never really felt right.

So I guess I'm fine with it either way. I think I'm just a bit annoyed that devtools has to exist. It feels like unnecessary documentation and maintenance overhead. But here we are. 🤷‍♂️

2024-04-10 01:30 UTC, emteknetnz commented
Closed in favor of https://github.com/silverstripe/silverstripe-graphql-devtools/pull/53

2024-04-10 01:30 UTC, closed without merging