Fix server error if not authenticated
silverstripe/silverstripe-graphql pull request #447
Opened 2022-02-24 16:14 UTC by lekoala

For context : https://github.com/silverstripe/silverstripe-framework/issues/9978

Here, my proposal is to return a consistent json response

2022-02-24 23:14 UTC, GuySartorelli commented
I'd hesitate to just catch all `Exception`s - if something does actually fail, this will now mean there's no log of the failure other than a context-less 500 response in access logs.

2022-02-25 07:36 UTC, lekoala commented
I can improve the pr to catch the specific message if needed

2022-04-08 04:44 UTC, GuySartorelli requested changes
The exception being caught is from `SilverStripe\GraphQL\Controller::getRequestUser()`:
https://github.com/silverstripe/silverstripe-graphql/blob/b51ce72bfc3508cda7fbbfb3a6587b50f09263c6/src/Controller.php#L427-L449
The exceptions were originally added to `index()` in #57.

We should probably also treat the "Not authorised" exception message in the same way.

In general I'm okay with this. If you're happy to make a change to check for the "Not authorised" message, and change the response code, I'll be happy to approve it. I'll probably ask someone more familiar with GraphQL to review it before I'd be comfortable merging.

Note that while @unclecheese did say it shouldn't require authentication at all in the issue, I don't have enough background on why the authentication checks were added in the first place, so I'm more comfortable with this approach.

2022-04-08 04:44 UTC, GuySartorelli commented on src/Extensions/IntrospectionProvider.php
> +                return (new HTTPResponse(json_encode(["error" => "Authentication required"]), 500))
500 isn't the right response code here.
```suggestion
                return (new HTTPResponse(json_encode(["error" => "Authentication required"]), 401))
```

2022-04-08 08:50 UTC, lekoala commented
> We should probably also treat the "Not authorised" exception message in the same way.

I don't think that's strictly necessary. I don't mind having logged in users get that kind of error page. My issue is that public endpoints can be visited by anyone (bots for example) and trigger errors that get logged for instance.

I think the current design works ok as long as the public use case is covered.

I've changed the error code as you requested.

2023-12-19 02:37 UTC, GuySartorelli commented
Sorry it's taken me so long to get back to this.
Please treat the "Not authorised" exception message the same way for consistency.
Please also target this to `3.8` so it can be released as a patch.

Once that's done I'll be happy to merge.

Alternatively if you don't plan on continuing with this PR please close it.

2023-12-22 08:27 UTC, lekoala commented
@GuySartorelli done

2023-12-22 08:36 UTC, GuySartorelli commented
Tha is for that. Unfortunately as mentioned in https://github.com/silverstripe/silverstripe-graphql/pull/447#pullrequestreview-935897300 the two scenarios news to return differen HTTP code (specifically 401 for "Authentication required" and 403 for "Not authorised")

Can you please make that change?

2023-12-22 09:47 UTC, lekoala commented
sorry i missed that one
done

2026-02-17 16:26 UTC, closed without merging