API Strongly type everything
silverstripe/silverstripe-graphql pull request #460
Opened 2022-04-26 11:06 UTC by maxime-rainville

Trying to strongly type everything.

# Parent issue
- https://github.com/silverstripe/silverstripe-graphql/issues/455

2022-04-26 11:20 UTC, GuySartorelli commented
In some cases you've removed the params and returns from phpdoc blocks and in other cases you e retained it. We should be consistent about that (and probably have at least a semiformal policy about it to make it easier on ourselves when it comes time to strongly type other modules)

2022-04-26 11:32 UTC, maxime-rainville reviewed
I try to strongly type everything.

There's a few places where array definition where clearly meant to be `callabale` so I swapped those.

When the PHPDoc was just repeating the explicit types, I removed it.

2022-04-26 11:32 UTC, maxime-rainville commented on src/Schema/DataObject/Plugin/DBFieldArgs/DBDateArgs.php
> +    public static function resolve(mixed $obj, array $args): DBField|string
Not supported in PHP7.4

```suggestion
    public static function resolve($obj, array $args)
```

2022-04-26 11:32 UTC, maxime-rainville commented on src/Middleware/QueryMiddleware.php
> +    public function process(Schema $schema, string $query, array $context, array $vars, callable $next): ExecutionResult|array;
```suggestion
    public function process(Schema $schema, string $query, array $context, array $vars, callable $next);
```

2022-04-26 11:32 UTC, maxime-rainville commented on src/QueryHandler/QueryHandler.php
> +    public function query(GraphQLSchema $schema, string|DocumentNode $query, ?array $vars = []): array
Not supported in PHP 7.4
```suggestion
    public function query(GraphQLSchema $schema, $query, ?array $vars = []): array
```

2022-04-26 11:32 UTC, maxime-rainville commented on src/QueryHandler/QueryHandler.php
> +    public function queryAndReturnResult(GraphQLSchema $schema, string|DocumentNode $query, ?array $vars = []): array|ExecutionResult
Not supported in PHP 7.4
```suggestion
    public function queryAndReturnResult(GraphQLSchema $schema, $query, ?array $vars = [])
```

2022-04-26 11:32 UTC, maxime-rainville commented on src/QueryHandler/QueryHandler.php
> +    protected function callMiddleware(GraphQLSchema $schema, string $query, array $context, array $params, callable $last): ExecutionResult|array
```suggestion
    protected function callMiddleware(GraphQLSchema $schema, string $query, array $context, array $params, callable $last)
```

2022-04-26 11:32 UTC, maxime-rainville commented on src/QueryHandler/QueryHandlerInterface.php
> +    public function query(Schema $schema, string|DocumentNode $query, array $params = []): array;
Not supported in PHP 7.4
```suggestion
    public function query(Schema $schema, $query, array $params = []): array;
```

2022-04-26 11:32 UTC, maxime-rainville commented on _config.php
> +Deprecation::notification_version('4.0.0', 'silverstripe/graphql');
I think this is meant to flag deprecation warning and should have been incremented in previous release.

2022-04-26 11:32 UTC, maxime-rainville commented on src/Auth/Handler.php
> +    public function requireAuthentication(HTTPRequest $request): Member|false
Not supported in PHP 7.4
```suggestion
    public function requireAuthentication(HTTPRequest $request)
```

2022-04-26 11:32 UTC, maxime-rainville commented on src/Middleware/Middleware.php
> -interface Middleware
I couldn't find this being used anywhere.

2022-04-26 11:32 UTC, maxime-rainville commented on src/Middleware/MiddlewareConsumer.php
> -trait MiddlewareConsumer
Couldn't find this being used anywhere.

2022-04-26 11:32 UTC, maxime-rainville commented on src/QueryHandler/QueryHandler.php
> -    const CURRENT_USER = 'currentUser';
Couldn't find a reference to this anywhere.

2022-04-26 11:32 UTC, maxime-rainville commented on src/Schema/DataObject/Plugin/InheritedPlugins.php
> -        }
This code snippet will never do anything because of the return statement above. It's been in the code base for over a year, so it should be safe to scarp it.

2022-04-27 00:46 UTC, GuySartorelli requested changes
I haven't gone through the whole PR 'cause it's pretty big - there's a lot of inconsistency about keeping or removing `@param` and `@returns` declarations in PHPDocs even when they match the typehints exactly.

There are also a couple of other small changes here (namely some missing typehints) - but again I haven't checked the whole PR much less had a hunt around outside the diff to see if there were others missed out.

2022-04-27 00:46 UTC, GuySartorelli commented on src/Config/Configuration.php
> +     * @param ?mixed $default
I think the PHPDoc way of declaring nullability is to use unions (i.e. `mixed|null`) - but in any case, [mixed is inherently nulalble.](https://wiki.php.net/rfc/mixed_type_v2#nullability)
```suggestion
     * @param mixed $default
```

2022-04-27 00:46 UTC, GuySartorelli commented on src/Config/ModelConfiguration.php
>       * @return string
```suggestion
```
We're removing these elsewhere - so we should be consistent. Also the `@param`s.

2022-04-27 00:46 UTC, GuySartorelli commented on src/Config/Configuration.php
> +     * @param ?mixed $default
`get()` doesn't seem to be declared higher in the inheritance than this (i.e. it's not in the trait) - but I'm guessing this wasn't typehinted for PHP7.4 compatability?

2022-04-27 00:46 UTC, GuySartorelli commented on src/Auth/MemberAuthenticator.php
>       * @return bool
```suggestion
```
These are the same as the typehints so we don't need the phpdocs.

2022-04-27 00:46 UTC, GuySartorelli commented on src/Controller.php
> -     * Override the default cors config per instance
What's the motivation for removing this comment?

2022-04-27 00:46 UTC, GuySartorelli commented on src/Controller.php
> -     * Process the CORS config options and add the appropriate headers to the response.
What's the motivation for removing this comment?

2022-04-27 00:46 UTC, GuySartorelli commented on src/Controller.php
>      protected function applyContext(QueryHandlerInterface $handler)
```suggestion
    protected function applyContext(QueryHandlerInterface $handler): void
```

2022-04-27 00:46 UTC, GuySartorelli commented on src/Controller.php
>      protected function handleOptions(HTTPRequest $request)
```suggestion
    protected function handleOptions(HTTPRequest $request): HTTPResponse
```

2022-04-27 00:46 UTC, GuySartorelli commented on src/Dev/Build.php
> +    public function build(HTTPRequest $request): void
Remove the `@param` in the phpdoc

2022-04-27 00:46 UTC, GuySartorelli commented on src/Dev/Build.php
> +    public function buildSchema(string $key = null, $clear = true): void
```suggestion
    public function buildSchema(string $key = null, bool $clear = true): void
```

2022-04-27 00:46 UTC, GuySartorelli commented on src/Dev/Build.php
>       * @param int $level
```suggestion
```
There isn't even a `$level` argument here.

2022-04-27 00:46 UTC, GuySartorelli commented on src/Extensions/DevBuildExtension.php
>       */
```suggestion
```

2022-04-27 00:46 UTC, GuySartorelli commented on src/Extensions/QueryRecorderExtension.php
>       * @param DataQuery $query
```suggestion
```

2022-04-27 00:46 UTC, GuySartorelli commented on src/Extensions/QueryRecorderExtension.php
>       * @param callable $callback
```suggestion
```

2022-04-27 00:46 UTC, GuySartorelli commented on src/Middleware/QueryCachingMiddleware.php
>       * @return $this
```suggestion
```

2022-04-27 00:46 UTC, GuySartorelli commented on src/Middleware/QueryCachingMiddleware.php
>       * @return string
```suggestion
```

2022-04-27 00:46 UTC, GuySartorelli commented on src/Middleware/QueryCachingMiddleware.php
>       * @return array|null
```suggestion
```
Also remove the `@param`

2022-04-27 00:46 UTC, GuySartorelli commented on src/Middleware/QueryCachingMiddleware.php
>       * @param array $classesUsed
```suggestion
```
Also remove the `@param $key`

2022-04-27 00:46 UTC, GuySartorelli commented on src/Middleware/QueryMiddleware.php
>       * @param callable $next
```suggestion
```
Also remove the other `@param`s

2022-04-27 00:46 UTC, GuySartorelli commented on src/PersistedQuery/FileProvider.php
>       * @return array
```suggestion
```

2022-04-28 22:01 UTC, maxime-rainville commented
Just pushed a few extra changes to explicitly require all the libraries directly reference in the codebase and to make Versioned optional.

2022-04-28 22:05 UTC, maxime-rainville commented on src/Config/Configuration.php
> +     * @param ?mixed $default
Are you asking why I didn't add a explicit `:mixed` return type?

`mixed` doesn't exists in PHP7.4.

2022-04-28 22:10 UTC, GuySartorelli commented on src/Config/Configuration.php
> +     * @param ?mixed $default
Yup, and yeah that's what I thought was probably the case. No issue there then :) Just gotta fix the phpdoc from`?mixed` to `mixed`

2022-04-28 22:31 UTC, maxime-rainville commented on src/Controller.php
> -     * Override the default cors config per instance
I brought it back.

2022-04-28 22:31 UTC, maxime-rainville commented on src/Controller.php
> -     * Process the CORS config options and add the appropriate headers to the response.
Brought it back.

2022-04-28 22:31 UTC, maxime-rainville commented on src/Dev/Build.php
> +    public function build(HTTPRequest $request): void
Done

2022-04-28 22:37 UTC, GuySartorelli requested changes
You've still got a _lot_ of PHPDocs here that are duplicating (and in at least one case in conflict with) the strong param and/or return types. I'm not going to go through and ping them all in the review because you'll still have to go through and find them all in your IDE to remove them, so it's just duplication of effort.
Consider this a blanket "Please remove the PHPDocs `param` and `return` declarations that are the same as the strong typehints, and validate any that are in conflict.

2022-04-28 22:37 UTC, GuySartorelli commented on src/Config/Configuration.php
> +     * @param mixed|null $default
Mixed is still inherently nullable - no need to declare null as an option here.
That said it's not the end of the world if you don't end up changing this. Call it an optional requested change :p

2022-04-28 22:37 UTC, GuySartorelli commented on src/PersistedQuery/FileProvider.php
>       * @return string
This isn't even correct according to your stong typed return type - please remove these params and return type PHPDocs.

2022-04-28 22:37 UTC, GuySartorelli commented on src/PersistedQuery/FileProvider.php
>       * @param array $mapping
```suggestion
```

2022-04-28 22:37 UTC, GuySartorelli commented on src/PersistedQuery/FileProvider.php
>       * @return $this
```suggestion
```

2022-04-28 23:14 UTC, emteknetnz requested changes

2022-04-28 23:14 UTC, emteknetnz commented on src/Auth/BasicAuthAuthenticator.php
>              return BasicAuth::requireLogin($request, 'Restricted resource');
```suggestion
            return BasicAuth::requireLogin($request, 'Restricted resource') ?: null;
```

`BasicAuth::requireLogin()` can also return bool

https://github.com/silverstripe/silverstripe-framework/blob/4/src/Security/BasicAuth.php#L114

2022-04-28 23:14 UTC, emteknetnz commented on src/Schema/DataObject/Plugin/Paginator.php
> +    private static $resolver = [__CLASS__, 'paginate'];
```suggestion
    private static callable $resolver = [__CLASS__, 'paginate'];
```

2022-04-28 23:14 UTC, emteknetnz commented on src/Schema/Plugin/PaginationPlugin.php
> +    private static ?array $resolver = null;
```suggestion
    private static ?callable $resolver = null;
```

2022-04-28 23:14 UTC, emteknetnz commented on src/Schema/Plugin/SortPlugin.php
> +    private static array $resolver = [__CLASS__, 'sort'];
```suggestion
    private static callable $resolver = [__CLASS__, 'sort'];
```

2022-04-28 23:14 UTC, emteknetnz commented on src/Schema/Type/Type.php
> +    private ?string  $description = null;
```suggestion
    private ?string $description = null;
```

2022-04-28 23:19 UTC, GuySartorelli commented on src/Schema/Plugin/SortPlugin.php
> +    private static array $resolver = [__CLASS__, 'sort'];
In `PaginationPlugin` the resolver callable is nullable - should that be the case here too?

2022-04-28 23:28 UTC, maxime-rainville commented on src/Config/Configuration.php
> +     * @param mixed|null $default
```suggestion
     * @param mixed $default
```

2022-04-28 23:32 UTC, maxime-rainville commented on src/Schema/DataObject/Plugin/Paginator.php
> +    private static $resolver = [__CLASS__, 'paginate'];
I tried that initially, but I was getting errors thrown back in my face.

2022-04-28 23:32 UTC, maxime-rainville commented on src/Schema/Logger.php
> +    public function alert($message, array $context = [])
That's define in the interface.

2022-04-28 23:33 UTC, maxime-rainville commented on src/Schema/Logger.php
> +    public function critical($message, array $context = [])
That's define in the interface.

2022-04-28 23:33 UTC, maxime-rainville commented on src/Schema/Logger.php
> +    public function emergency($message, array $context = [])
That's define in the interface.

2022-04-28 23:33 UTC, maxime-rainville commented on src/Schema/Logger.php
> +    public function error($message, array $context = [])
That's define in the interface.

2022-04-28 23:33 UTC, maxime-rainville commented on src/Schema/Logger.php
> +    public function info($message, array $context = [])
That's define in the interface.

2022-04-28 23:33 UTC, maxime-rainville commented on src/Schema/Logger.php
> +    public function log($level, $message, array $context = [])
That's define in the interface.

2022-04-28 23:33 UTC, maxime-rainville commented on src/Schema/Logger.php
> +    public function notice($message, array $context = [])
That's define in the interface.

2022-04-28 23:33 UTC, maxime-rainville commented on src/Schema/Logger.php
> +    public function warning($message, array $context = [])
That's define in the interface.

2022-04-28 23:36 UTC, maxime-rainville commented on src/Schema/Plugin/PaginationPlugin.php
> +    private static ?array $resolver = null;
I was getting errors thrown in my face when I had callable there. I'm thinking I probably should remove the array typing as well because not all `callabale` will be array either.

2022-04-28 23:36 UTC, maxime-rainville commented on src/Schema/Plugin/PaginationPlugin.php
> +    private static ?array $resolver = null;
```suggestion
    private static $resolver = null;
```

2022-04-28 23:37 UTC, maxime-rainville commented on src/Schema/Plugin/SortPlugin.php
> +    private static array $resolver = [__CLASS__, 'sort'];
```suggestion
    private static $resolver = [__CLASS__, 'sort'];
```

2022-04-28 23:40 UTC, maxime-rainville commented on src/Schema/Logger.php
> +    public function debug($message, array $context = [])
That's define in the interface.

2022-05-02 21:39 UTC, maxime-rainville commented on .travis.yml
> +      env: DB=MYSQL PHPUNIT_TEST=1 PHPUNIT_COVERAGE_TEST=1
We'll remove this for now until we can figure out what the problem with the segmentation fault is.

```suggestion
    - # php: 8.0
      # env: DB=MYSQL PHPUNIT_TEST=1 PHPUNIT_COVERAGE_TEST=1
```

2022-05-02 21:40 UTC, maxime-rainville commented on src/QueryHandler/QueryHandler.php
> +     * @var ?callable
PHPDoc doesn't allow the ?callable syntax.
```suggestion
     * @var callable | null
```

2022-05-02 21:42 UTC, emteknetnz commented on .travis.yml
> +      env: DB=MYSQL PHPUNIT_TEST=1 PHPUNIT_COVERAGE_TEST=1
Just update your matrix to what was match what was recently committed - https://github.com/silverstripe/silverstripe-graphql/blob/master/.travis.yml#L12, PHP_COVERAGE_TEST was removed

2022-05-02 21:42 UTC, maxime-rainville commented on src/PersistedQuery/FileProvider.php
>       * @return string
```suggestion
```

2022-05-03 00:22 UTC, GuySartorelli requested changes
Still a _lot_ of types mentioned in PHPDocs. I've gone through and tagged them this time.
Note that in some cases it's possible that removing just the bits I've pinged will result in an empty PHPDoc - in those cases the whole PHPDoc should be thrown out.

I did find some missing types (see comments)

There's also a question in here about typing callables as `array`.

2022-05-03 00:22 UTC, GuySartorelli commented on src/Schema/Schema.php
> +    private static array $pluraliser = [self::class, 'pluraliser'];
Elsewhere for callable as an array in config you've just left it untyped. If typing config as `callable` gives legitimate errors, I'd prefer it be left untyped. Also the `@var` phpdoc should categorically say `callable` - we don't want arbitrary arrays being set here if we can help it, and the phpdoc is a good way to indicate the intention where strong typing doesn't work as expected.

2022-05-03 00:22 UTC, GuySartorelli commented on src/Schema/Schema.php
>      private function applyComponentUpdatesFromSet(array $componentSet)
```suggestion
    private function applyComponentUpdatesFromSet(array $componentSet): void
```

2022-05-03 00:22 UTC, GuySartorelli commented on src/Schema/Services/NestedInputBuilder.php
>      private $fieldFilter;
```suggestion
    private ?callable $fieldFilter;
```

2022-05-03 00:22 UTC, GuySartorelli commented on src/Schema/Services/NestedInputBuilder.php
>      /**
```suggestion
```

2022-05-03 00:22 UTC, GuySartorelli commented on src/Schema/Services/NestedInputBuilder.php
>      private $leafNodeHandler;
```suggestion
    private ?callable $leafNodeHandler;
```

2022-05-03 00:22 UTC, GuySartorelli commented on src/Schema/Services/NestedInputBuilder.php
>      private $typeNameHandler;
```suggestion
    private ?callable $typeNameHandler;
```

2022-05-03 00:22 UTC, GuySartorelli commented on src/Schema/Services/NestedInputBuilder.php
>      /**
```suggestion
```

2022-05-03 00:22 UTC, GuySartorelli commented on src/Schema/Services/NestedInputBuilder.php
>      /**
```suggestion
```

2022-05-03 00:22 UTC, GuySartorelli commented on src/Schema/Services/NestedInputBuilder.php
>      private $leafNodeHandler;
Note: If there's a valid reason for not typing these please indicate what that is and update the phpdoc typing to `callable|null`

2022-05-03 00:22 UTC, GuySartorelli commented on src/Schema/Storage/CodeGenerationStore.php
>       * If true, s
Would you mind fixing this comment?

2022-05-03 00:22 UTC, GuySartorelli commented on src/Schema/Type/Enum.php
> +     * @param mixed|null $val
```suggestion
     * @param mixed $val
```
Mixed is inherently nullable

2022-05-03 00:22 UTC, GuySartorelli commented on src/Schema/Type/Enum.php
>       * @return Enum
```suggestion
```

2022-05-03 00:22 UTC, GuySartorelli commented on src/Schema/Type/Enum.php
>       * @param $key
```suggestion
```

2022-05-03 00:22 UTC, GuySartorelli commented on src/Schema/Type/Type.php
>       */
```suggestion
```

2022-05-03 00:22 UTC, GuySartorelli commented on src/Schema/Type/TypeReference.php
>      private $defaultValue;
If this is mixed then it would be appropriate to update the phpdoc to `@var mixed` instead of removing it - otherwise it should be typed appropriately.

2022-05-03 00:22 UTC, GuySartorelli commented on src/Schema/Type/TypeReference.php
> -     */
I think this is worth keeping - it indicates that we didn't just forget to type this one, but that its typing is mixed which isn't supported in php7.4.
Gives developers confidence that it can be any type intentionally rather than accidentally.

2022-05-03 00:34 UTC, maxime-rainville commented on .travis.yml
> +    #  env: DB=MYSQL PHPUNIT_TEST=1 PHPUNIT_COVERAGE_TEST=1
This use to be on PostgreSQL. I tried to move it to MySQL to see if it would make a difference. Se technically we are not removing anything

2022-05-03 00:46 UTC, maxime-rainville commented on src/QueryHandler/QueryHandler.php
> +    private ?array $errorHandler = null;
```suggestion
    private $errorHandler = null;
```

2022-05-03 00:52 UTC, GuySartorelli commented on .travis.yml
> +    #  env: DB=MYSQL PHPUNIT_TEST=1 PHPUNIT_COVERAGE_TEST=1
There's a separate `PGSQL` entry above this though? I'm confused...
In any case looking at the whole file instead of just the changes I do see there's a separate PHP 8.0 MYSQL phpunit test being done. So I'd say the coverage test should probably be tacked on the end of that if-and-when we reinstate it rather than duplicating that _just_ for coverage.

In other words: Remove these commented-out lines altogether, and add `#PHPUNIT_COVERAGE_TEST=1` to the end of line 20

That said, if you'd prefer to just keep these lines here it's not the end of the world, so you can just comment to that effect and I'll consider this part resolved.

2022-05-03 00:53 UTC, GuySartorelli commented on src/QueryHandler/QueryHandler.php
> +    private ?array $errorHandler = null;
Are there errors happening when you type this as `callable` (or `?callable`)? I can understand that happening on a config (`i.e. `private static`) variable, but it seems to me that it should be valid here?

2022-05-03 00:56 UTC, maxime-rainville commented on src/QueryHandler/QueryHandler.php
> +    private ?array $errorHandler = null;
I've removed the explicit typing here. Because this is a plain `private` property, it's not part of our API we can change it afterwards if we want.

2022-05-03 00:58 UTC, GuySartorelli commented on src/QueryHandler/QueryHandler.php
> +    private ?array $errorHandler = null;
I _guess_ that's okay.... I'd prefer to understand if there's some issue with it being `callable` though. If there is, that should at least be documented to be fixed if necessary - and if there's no issue with it, then having that type declared will be useful for us when we work on it.

2022-05-03 02:28 UTC, maxime-rainville commented on src/Schema/DataObject/Plugin/CanViewPermission.php
>       * @param ResolveInfo $info
`mixed` and union types are not supported in PHP7.4

2022-05-03 02:31 UTC, GuySartorelli commented on src/Schema/DataObject/Plugin/CanViewPermission.php
>       * @param ResolveInfo $info
Looking at these params, `array`, `array`, `ResolveInfo`.... these aren't mixed or union types. Am I missing something here?

2022-05-03 02:31 UTC, maxime-rainville commented on src/Schema/DataObject/Plugin/Paginator.php
> +    private static $resolver = [__CLASS__, 'paginate'];
https://stackoverflow.com/a/57935949/10936596

2022-05-03 02:32 UTC, GuySartorelli commented on src/Schema/DataObject/Plugin/CanViewPermission.php
>       * @param ResolveInfo $info
Nevermind - for some reason when I looked at it before I thought _none_ of the parameters were strongly typed but I was mistaken.

2022-05-03 02:43 UTC, maxime-rainville commented on src/Schema/Resolver/EncodedResolver.php
> +        $this->context = $context ?: [];
I tried to explicitiely cast `private $context` above as a non-nullable array. But then I started getting errors from test passing `null`.  I think the proper fix here is to say that private $context is nullable. I'll do that.

2022-05-03 02:47 UTC, maxime-rainville commented on src/Schema/Storage/CodeGenerationStore.php
>       * If true, s
Don't know what the comment was meant to say, so I'll just remove it.

2022-05-03 02:52 UTC, GuySartorelli commented on src/Schema/Resolver/EncodedResolver.php
> +        $this->context = $context ?: [];
So long as that doesn't cause any issues where the `context` property is used...

2022-05-03 03:14 UTC, GuySartorelli commented on src/QueryHandler/QueryHandler.php
> +    private ?array $errorHandler = null;
For the sake of anyone reading this in the future: `callable` is not supported as a typehint for properties. [Explanation here](https://stackoverflow.com/a/57935949/10936596)

2022-05-03 03:34 UTC, GuySartorelli approved these changes
Looks good to me. A few phpdocs missed but we've agreed over slack that some redundant phpdocs here or there isn't the end of the world, and shouldn't block this PR being merged.

Merge on green.

2022-05-03 04:15 UTC, GuySartorelli commented
Behat failure is on master already, so not related to this PR.

2022-05-03 04:15 UTC, merged