[v4] Relax possible filter value types
silverstripe/silverstripe-graphql pull request #477
Opened 2022-06-21 11:12 UTC by bummzack

Fixes #476

2022-06-21 21:16 UTC, GuySartorelli commented on tests/Schema/DataObject/Plugin/FiltersTest.php
> +    public function testFilterArguments()
instead of calling `testFilter()`, this should return an array and should be named `filterProvider()`. Then you can put `@dataProvider filterProvider` in the PHDoc for `testFilter()` and phpunit will handle passing in the arguments in a way that tests each case even if one fails, and reports on failures in a useful way

2022-06-22 16:38 UTC, bummzack commented on tests/Schema/DataObject/Plugin/FiltersTest.php
> +    public function testFilterArguments()
@GuySartorelli Oh, that's something I didn't know. Neat! I've updated the test. Thanks for the heads up.

2022-06-22 21:58 UTC, GuySartorelli requested changes
Just a few more small changes to make and then we're good to go.

2022-06-22 21:58 UTC, ChloeSartorelli commented on tests/Schema/DataObject/Plugin/FiltersTest.php
> +            // Contains
Please remove these comments - it's clear from the class name of the filter which filter is being tested.

2022-06-22 21:58 UTC, ChloeSartorelli commented on tests/Schema/DataObject/Plugin/FiltersTest.php
> +    public function filterProvider(): array
```suggestion
    public function filterArgumentsProvider(): array
```
The convention tends to be that it matches the name of the test method that's using it like this.

2022-06-22 21:58 UTC, ChloeSartorelli commented on tests/Schema/DataObject/Plugin/FiltersTest.php
> +     * @dataProvider filterProvider
```suggestion
     * @dataProvider filterArgumentsProvider
```

2022-06-22 21:58 UTC, GuySartorelli commented on tests/Schema/DataObject/Plugin/FiltersTest.php
> +     * @return void
```suggestion
     * @dataProvider filterProvider
```
No need to have PHPDocs that duplicate the typings - these have a tendency to get out of date and since we have typehints they don't provide any extra information.

2022-06-22 21:58 UTC, GuySartorelli commented on tests/Schema/DataObject/Plugin/FiltersTest.php
> +    public function testFilterArguments(FieldFilterInterface $filter, string $identifier, array $params)
```suggestion
    public function testFilterArguments(FieldFilterInterface $filter, string $identifier, array $params): void
```

2022-06-23 06:46 UTC, bummzack commented on tests/Schema/DataObject/Plugin/FiltersTest.php
> +    public function testFilterArguments(FieldFilterInterface $filter, string $identifier, array $params)
I have addressed your code-quality improvements in the latest commit.

2022-06-23 07:09 UTC, GuySartorelli approved these changes
The only Travis failure is identical to the one happening on the 4.0 branch already https://app.travis-ci.com/github/silverstripe/silverstripe-graphql/builds/252256400 which is not related to this PR.

Thank you for fixing this, it's very much appreciated.

2022-06-23 07:11 UTC, merged