MNT Use GitHub Actions CI
silverstripe/silverstripe-graphql pull request #481
Opened 2022-07-05 06:42 UTC by emteknetnz

Issue https://github.com/silverstripe/gha-ci/issues/11<br /><br />Workflow run https://github.com/creative-commoners/silverstripe-graphql/actions?query=branch%3Apulls%2F3.8%2Fmodule-standards

2022-07-14 23:25 UTC, GuySartorelli requested changes

2022-07-14 23:25 UTC, GuySartorelli commented on .github/workflows/ci.yml
> +          endtoend_config: vendor/dnadesign/silverstripe-elemental/behat.yml
Why versioned and elemental? Those aren't mentioned in the travis config on this branch.
Also if we _should_ be including versioned-admin, should we do that for the 4.0 branch as well?

2022-07-14 23:25 UTC, GuySartorelli commented on composer.json
> +        "silverstripe/frameworktest": "^0.4.3"
Do we need to add versioned-admin and elemental as well?

2022-07-14 23:36 UTC, emteknetnz commented on .github/workflows/ci.yml
> +          endtoend_config: vendor/dnadesign/silverstripe-elemental/behat.yml
I'm just copying what was previously in the travis file

2022-07-14 23:39 UTC, emteknetnz commented on .github/workflows/ci.yml
> +          endtoend_config: vendor/dnadesign/silverstripe-elemental/behat.yml
oh, copied it from the wrong branch :-)

2022-07-14 23:44 UTC, emteknetnz commented on composer.json
> +        "silverstripe/frameworktest": "^0.4.3"
no, only supposed to have asset-admin in this one, have added to require-dev

2022-07-15 00:29 UTC, GuySartorelli approved these changes

2022-07-15 00:29 UTC, merged