FIX Don't error silently when arguments are enabled
silverstripe/silverstripe-graphql pull request #523
Opened 2023-03-09 22:39 UTC by GuySartorelli

If PHP is configured to include arguments, the `json_encode($result)` call in graphql's error handling was hitting a recursion error (specifically found while validating https://github.com/silverstripe/silverstripe-graphql/issues/500).

This PR avoids that problem entirely by treating the backtrace the same as we do everywhere else in framework. It also ensures that arguments are filtered appropriately to avoid leaking sensitive information.

## Issue
- https://github.com/silverstripe/silverstripe-graphql/issues/522

2023-04-03 03:39 UTC, emteknetnz requested changes
Can we add a unit-test that will cause an exception that has a >10000 character argument and assert than it's truncating the argument in the backtrace?

2023-04-03 22:45 UTC, GuySartorelli commented
Rather than doing this with a real exception, I'm just going to pass in a mocked exception trace into the new private method.
It's a good idea to validate that method in a unit test or 2 anyway to ensure it stays up to date with the `BackTrace` class.

2023-04-04 01:53 UTC, GuySartorelli commented
Added backtrace test

2023-04-04 01:57 UTC, GuySartorelli commented
CI failures are because there's no version of `silverstripe/installer` with constraints that are happy with the `4.2.x-dev` constraint for this module.

2023-04-04 02:34 UTC, emteknetnz approved these changes
Confirmed all the graphql unit-tests are passing locally

2023-04-04 02:35 UTC, merged