FIX: Don't 403 error when origin is on CORS-disallowed (fixes #519)
silverstripe/silverstripe-graphql pull request #527
Opened 2023-03-20 12:58 UTC by kinglozzer

This will no longer output a 403 error if origin is invalid - CORS headers are to protect things client side, not server side, so there’s no security benefit in triggering this error.

The `Access-Control-Allow-Origin` is now only output if the origin is valid. For valid origins, that matches the current behaviour. For invalid origins, this is a behavioural change (it used to 403) but this new behaviour will correctly trigger preflight errors:

> Access to XMLHttpRequest at 'http://my-graphql-server.test/' from origin 'http://my-origin.test' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

One other minor behavioural change here - if developer has opted to allow all origins, this will now explicitly output `Access-Control-Allow-Origin: *` instead of `Access-Control-Allow-Origin: <current origin>`

## Issue
- #519

2023-03-20 13:58 UTC, lozcalver commented on src/Controller.php
> +                $response->addHeader('Vary', 'Origin');
This is new, based on the advice here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#cors_and_caching

2023-04-24 10:23 UTC, lozcalver commented
bump

2023-05-01 21:35 UTC, GuySartorelli commented
The issue attached to this PR is in our "backlog with PRs" column and will be refined in a future backlog refinement session.

2023-06-20 05:39 UTC, emteknetnz requested changes
Looking at the the original issue this was to allow for use case where there is no Origin header being sent.

It seems like you can **almost** already do that by update the config on the private static `$cors['Allow-Origin']` to include a `*` in there to allow this? `validateOrigin()` will return true if it encounters a `*` -- however `$origin` needs to be non-empty which is what prevents this now

This PR seems like it's completely disabling Origin validation though, based on the discussion in the original issue it looks like it's assumption that doing origin validation at this point is wrong?  I'm not so sure it is?  Seems like we're better of keeping this existing origin validation.

I think all we really need to do in this PR is instead update `validateOrigin()` to return `true` if origin is empty but there's a `*` in the static config

2023-06-29 21:59 UTC, emteknetnz commented
@kinglozzer Let me know if you're going to continue with this PR, otherwise I'll close this one for now

2023-06-30 08:01 UTC, kinglozzer commented
Not likely to have time soon 😔

2023-06-30 08:01 UTC, closed without merging