ENH Rebuild schema if file missing
silverstripe/silverstripe-graphql pull request #530
Opened 2023-03-22 05:09 UTC by emteknetnz

2023-03-22 05:38 UTC, michalkleiner commented on src/Schema/Storage/AbstractTypeRegistry.php
> +    public const REBUILD_ON_MISSING_FILENAME = '__rebuild_on_missing';
Does the constant need to be public?

2023-03-22 05:38 UTC, michalkleiner commented on src/Schema/Storage/AbstractTypeRegistry.php
> +     * This is a fallback in addition the to regular fallback of building the schema
```suggestion
     * This is a fallback in addition to the regular fallback of building the schema
```

2023-03-22 05:41 UTC, michalkleiner commented on src/Schema/Storage/AbstractTypeRegistry.php
> +    public const REBUILD_ON_MISSING_FILENAME = '__rebuild_on_missing';
Ah, for the test. I would probably swap the visibility around and have the constant private or actually just put the value directly in `getRebuildOnMissingPath` and have that method public.

2023-03-22 05:44 UTC, michalkleiner commented on src/Schema/Storage/AbstractTypeRegistry.php
> +    public const REBUILD_ON_MISSING_FILENAME = '__rebuild_on_missing';
That would probably have other complications in the test.. all good. Just rubber ducking here.

2023-03-22 05:45 UTC, emteknetnz commented on src/Schema/Storage/AbstractTypeRegistry.php
> +     * This is a fallback in addition the to regular fallback of building the schema
Updated

2023-03-23 22:43 UTC, GuySartorelli requested changes
Works well locally - I wasn't able to trigger [CVE-2023-28104](https://www.silverstripe.org/download/security-releases/cve-2023-28104) because the interval stopped the cache from being rebuilt. After enough time passed that the interval was exceeded, it rebuilt schema again.

Some changes to make

2023-03-23 22:43 UTC, ChloeSartorelli commented on src/Schema/Storage/AbstractTypeRegistry.php
> +     * Whether to rebuild the schema if there is a mysteriously missing schema file
```suggestion
     * Whether to rebuild the schema if there is a mysteriously missing schema file.
```

2023-03-23 22:43 UTC, ChloeSartorelli commented on src/Schema/Storage/AbstractTypeRegistry.php
> +     * Minimum number of seconds between rebuilding the schema if a schema file is missing
```suggestion
     * Minimum number of seconds between rebuilding the schema if a schema file is missing.
```

2023-03-23 22:43 UTC, ChloeSartorelli commented on src/Schema/Storage/AbstractTypeRegistry.php
> +                file_put_contents($path, time());
The whole point of this is that we can't rely on files in this folder existing when they should - which means we can't rely on _this_ file existing there when it should, either.

But at the same time, we can't store it in the silverstripe-cache dir (either indirectly via the cache API or directly with file_put_contents), because that might be shared between servers and we want this to be a "per graphql cache dir" operation.... so I think this is the best we can do.

Not merging just yet so you have a chance to respond if you have anything to add about this approach.

2023-03-23 22:43 UTC, ChloeSartorelli commented on src/Schema/Storage/AbstractTypeRegistry.php
> +     * Whether to rebuild the schema if there is a mysteriously missing schema file
Won't hold off merging for this, though, if it's not done.

2023-03-23 22:43 UTC, ChloeSartorelli commented on src/Schema/Storage/AbstractTypeRegistry.php
> +     * Minimum number of seconds between rebuilding the schema if a schema file is missing
Won't hold off merging for this, though, if it's not done.

2023-03-23 22:43 UTC, GuySartorelli commented on tests/Schema/AbstractTypeRegistryTest.php
> +        list($registry, , $method) = $this->getInstance();
Is that extra comma there to avoid some second value? If so, put a variable name there (`_` is often used) to indicate that the comma is intentional. It looks like a typo right now.

2023-03-23 22:43 UTC, GuySartorelli commented on tests/Schema/AbstractTypeRegistryTest.php
> +        })->removeGraphqlController();
`(new ClassName)->` does work, but it's pretty esoteric and makes it look like there's some extra magic going on. I'd prefer the object be captured in a variable, and then call the method on the variable.
That said, I won't hold back merging if you don't change this.

Also same thing in testRebuildOnMissing() below.

Note: This only applies if the controller API change I suggested doesn't work.

2023-03-23 22:43 UTC, GuySartorelli commented on tests/Schema/AbstractTypeRegistryTest.php
> +                }
Can't you just do:
```php
if (Controller::has_curr() && (Controller::curr() instanceof GraphQLController) {
    Controller::curr()->popCurrent();
}
```
If this works, please do it instead - prefer using existing API where it exists, and avoids having to have this anonymous class altogether.

2023-03-23 22:43 UTC, GuySartorelli commented on src/Schema/Storage/AbstractTypeRegistry.php
> +    public const REBUILD_ON_MISSING_FILENAME = '__rebuild_on_missing';
This doesn't need to be public - your test that requires it instantiates an anonymous subclass of `AbstractTypeRegistry` - just add a new public method to that anonymous class that returns the value of this constant.

2023-03-23 22:43 UTC, GuySartorelli commented on tests/Schema/AbstractTypeRegistryTest.php
> +        list($registry, , $method) = $this->getInstance();
```suggestion
        list($registry, , $getRebuildOnMissingPath) = $this->getInstance();
```
Make it really clear what method you're calling, without having to go look at the implementation of `getInstance()`

Feel free to also add "method" or "reflection" in the variable name if you want to, to distinguish this reflection method from the boolean result of calling the method.

2023-03-23 22:43 UTC, GuySartorelli commented on tests/Schema/AbstractTypeRegistryTest.php
> +        list($registry, $method) = $this->getInstance();
```suggestion
        list($registry, $canRebuildOnMissing) = $this->getInstance();
```
Make it clear what the method is

2023-03-23 22:43 UTC, GuySartorelli commented on tests/Schema/AbstractTypeRegistryTest.php
> +                }
Cant you just call `$graphqlConroller->pushCurrent()`? If the problem is there's no session, just instantiate a dummy `Session` object and add it to the controller.

2023-03-23 22:43 UTC, GuySartorelli commented on tests/Schema/AbstractTypeRegistryTest.php
> +        $graphqlConroller = new GraphQLController('test');
```suggestion
        $graphqlController = new GraphQLController('test');
```

2023-03-23 22:43 UTC, GuySartorelli commented on tests/Schema/AbstractTypeRegistryTest.php
> +                'message' => 'Controller false',
This (and the other messages below) is not a clear message to output with a PHPunit failure. What is actually being tested here, so that someone debugging a failure knows what needs to be fixed? What does "controller false" imply?

I'm guessing this should be something like "If the current controller is not a GraphQLController the schema should not be rebuilt"

2023-03-23 22:43 UTC, GuySartorelli commented on tests/Schema/AbstractTypeRegistryTest.php
> +                'expected' => false,
Should config be true here? Otherwise it could be false just because config is false, right?

2023-03-23 23:17 UTC, michalkleiner commented on src/Schema/Storage/AbstractTypeRegistry.php
> +                file_put_contents($path, time());
So when the schema doesn't exist and the write permissions to the `.graphql-generated` folder are lost, this is still subject to DDoS, right? Even if say a schema was committed to the repo and deployed but used a different than expected obfuscator.

2023-03-23 23:19 UTC, michalkleiner commented on tests/Schema/AbstractTypeRegistryTest.php
> +        list($registry, , $method) = $this->getInstance();
Can also be done as `[$registry, $_, $method] = $this->getInstance();` using the array syntax.

2023-03-23 23:22 UTC, michalkleiner commented on tests/Schema/AbstractTypeRegistryTest.php
> +        list($registry, , $method) = $this->getInstance();
Based on other uses of the `$this->getInstance()`, it seems like the comma is extra by mistake. The array syntax suggestion is still applicable though.

2023-03-23 23:30 UTC, emteknetnz commented on tests/Schema/AbstractTypeRegistryTest.php
> +                }
I dunno, it's messy either way.  
I think it would something like

```php
$fakeSession = new Session();
$graphqlController = new GraphQLController();
$request = Controller::curr()->getRequest();
$request->setSession($fakeSession);
$graphqlController->setRequest($request);
$graphqlController->pushCurrent();
```
That's way worse IMO, basically can't tell what's going on there.

2023-03-23 23:33 UTC, emteknetnz commented on tests/Schema/AbstractTypeRegistryTest.php
> +        })->removeGraphqlController();
$myInst = (new Class ...
{
  //...
});
$myInst->removeGraphqlController();

Surely is really no improvement

In my head makes more sense to NOT store anonymous classes (and functions) in variables

2023-03-23 23:37 UTC, GuySartorelli commented on src/Schema/Storage/AbstractTypeRegistry.php
> +                file_put_contents($path, time());
If the entire schema doesn't exist, this doesn't apply - that's a (slightly) different mechanism and will only trigger a rebuild once. This mechanism is for if _that_ mechanism doesn't get triggered because it's just the one specific shvema file that's missing.

If write permissions are lost then the will not rebuild (see is writable check in `canRebuildOnMissing()`)

If a different obfuscator was used this should trigger once - and only rebuild if all the checks in the above mentioned method pass.

2023-03-23 23:38 UTC, GuySartorelli commented on tests/Schema/AbstractTypeRegistryTest.php
> +                }
Imo that's much better, because we're using established API

2023-03-24 00:47 UTC, michalkleiner commented on src/Schema/Storage/AbstractTypeRegistry.php
> +                file_put_contents($path, time());
Right, I didn't put the write check in the `canRebuildOnMissing` method together with this, all good.

2023-03-24 00:49 UTC, michalkleiner commented on tests/Schema/AbstractTypeRegistryTest.php
> +                }
`src/Dev/TestSession.php` has nearly identical bit, so I'd support sticking with that...

```
$this->session = Injector::inst()->create(Session::class, []);
$this->cookies = Injector::inst()->create(Cookie_Backend::class);
$request = new HTTPRequest('GET', '/');
$request->setSession($this->session());
$this->controller = new Controller();
$this->controller->setRequest($request);
$this->controller->pushCurrent();
$this->controller->doInit();
```

2023-03-24 00:50 UTC, michalkleiner commented on tests/Schema/AbstractTypeRegistryTest.php
> +                }
Creating a dummy request with a dummy session is quite common in tests.

2023-03-24 07:17 UTC, emteknetnz commented on src/Schema/Storage/AbstractTypeRegistry.php
> +     * Whether to rebuild the schema if there is a mysteriously missing schema file
Updated

2023-03-24 07:17 UTC, emteknetnz commented on src/Schema/Storage/AbstractTypeRegistry.php
> +     * Minimum number of seconds between rebuilding the schema if a schema file is missing
Updated

2023-03-24 07:21 UTC, emteknetnz commented on tests/Schema/AbstractTypeRegistryTest.php
> +        list($registry, , $method) = $this->getInstance();
Extra comma was intentional, have added $_

2023-03-24 07:24 UTC, emteknetnz commented on tests/Schema/AbstractTypeRegistryTest.php
> +                }
It won't, because Controller::curr() is a Controller

This is only a unit test, we don't need to overthink this

2023-03-24 07:31 UTC, GuySartorelli commented on tests/Schema/AbstractTypeRegistryTest.php
> +                }
But you added a `GraphQLController` to the stack.
While this is a unit test, it should both be readable and as standard as we can reasonably make it.
Having esoteric or unusual syntax makes it look like something special is happening, and that the normal API won't work.

Not only does this add confusion, it also means that if we change the implementation details we might at best have to change this test and at worst have a test that's passing when the actual behaviour doesn't work.

2023-03-24 07:37 UTC, emteknetnz commented on src/Schema/Storage/AbstractTypeRegistry.php
> +    public const REBUILD_ON_MISSING_FILENAME = '__rebuild_on_missing';
Needs to be at least protected for that to work.   Also can't use reflection as https://www.php.net/manual/en/reflectionclass.getconstant.php simply returns the value, rather that property/method which lets you to call setAccessible()

Not much difference between protected vs public as they're both API, so may as well just leave public

2023-03-24 07:37 UTC, emteknetnz commented on tests/Schema/AbstractTypeRegistryTest.php
> +        list($registry, , $method) = $this->getInstance();
Updated

2023-03-24 07:37 UTC, emteknetnz commented on tests/Schema/AbstractTypeRegistryTest.php
> +        list($registry, $method) = $this->getInstance();
Updated

2023-03-24 07:38 UTC, emteknetnz commented on tests/Schema/AbstractTypeRegistryTest.php
> +        $graphqlConroller = new GraphQLController('test');
Updated

2023-03-24 07:40 UTC, emteknetnz commented on tests/Schema/AbstractTypeRegistryTest.php
> +                'message' => 'Controller false',
I just deleted the message, it was basically just for debugging

2023-03-24 07:40 UTC, emteknetnz commented on tests/Schema/AbstractTypeRegistryTest.php
> +                'expected' => false,
Updated

2023-03-24 07:48 UTC, emteknetnz commented on tests/Schema/AbstractTypeRegistryTest.php
> +                }
Updated

2023-03-24 07:51 UTC, emteknetnz commented on tests/Schema/AbstractTypeRegistryTest.php
> +                }
Updated

2023-03-24 07:51 UTC, emteknetnz commented on tests/Schema/AbstractTypeRegistryTest.php
> +        })->removeGraphqlController();
Has been refactored away

2023-03-24 08:07 UTC, emteknetnz commented on src/Schema/Storage/AbstractTypeRegistry.php
> +    public const REBUILD_ON_MISSING_FILENAME = '__rebuild_on_missing';
Changed to private method and set accessible via reflection

Using a method as private properties and constants can't seem to be set accessible via reflection, though methods can

2023-03-26 20:11 UTC, GuySartorelli approved these changes
Looks good to me.
I've rerun failed jobs now that the issue with admin is resolved. Merge on green.

2023-03-26 21:40 UTC, GuySartorelli commented
behat tests are failing repeatedly

2023-03-27 01:14 UTC, emteknetnz commented
It's an existing_ failure - https://github.com/silverstripe/silverstripe-graphql/actions/runs/4527398776/jobs/7973214759

Note: After approval I added a little bit to filter out Exception so that they match a particular message.  This isn't as good as using a new Exception type, but I didn't want to change the API via changing the Exception thrown, and the message is very unlikely to ever change - https://github.com/silverstripe/silverstripe-graphql/compare/f796b4fd49fbbe6d1b2062d239842a9eea668e6d..0b876c8e2c50f7d69c1eb4805edb5e1de49e5888

2023-03-27 01:19 UTC, GuySartorelli approved these changes
Approved a second time.
I'd have preferred a new exception - maybe for CMS 6 we can look at adding explicit exceptions in appropriate places for this module. For now the message check is sufficient.

2023-03-27 01:19 UTC, merged