NEW Enable storing graphql schema in `silverstripe-cache/`
silverstripe/silverstripe-graphql pull request #534
Opened 2023-05-03 04:50 UTC by GuySartorelli

## Issue
- https://github.com/silverstripe/silverstripe-graphql/issues/529

2023-05-15 23:39 UTC, GuySartorelli commented on src/Schema/Storage/CodeGenerationStore.php
> +            TEMP_PATH,
Note that `TEMP_FOLDER` and `TEMP_PATH` evaluate to the same value - but `TEMP_FOLDER` is deprecated.

2023-06-26 00:29 UTC, emteknetnz requested changes

2023-06-26 00:29 UTC, emteknetnz commented on src/Schema/Storage/CodeGenerationStore.php
> +        } else {
Seems a bit weird that we're splitting the code path here?  Seems that `$dest->getDirectory` would return something like `/tmp/silverstripe-.../.graphql-generated`, so why aren't we aren't we just treating the that dir the same way we currently treat `BASE_PATH/.graphql-generated`.  In particular there's the line `$fs->mirror($dest, $temp);` which is only present in the `dirNameIsDefined()` code path, I'm not sure what this line is supposed to do, though presumably _something_, though it seems concerning to me that it's not in the `!dirNameIsDefined()` code path

2023-06-26 00:29 UTC, emteknetnz commented on src/Schema/Storage/CodeGenerationStore.php
> +        if ($this->dirNameIsDefined()) {
As noted above, seems weird that we're have a different code paths depending on which directory the schema is stored in, ideally we'd treat everything the same

2023-06-26 00:29 UTC, emteknetnz commented on src/Schema/Storage/CodeGenerationStore.php
> +    private function createNewTempSchema(FileSystem $fs, string $tempDir)
```suggestion
    private function createNewTempSchema(FileSystem $fs, string $tempDir): void
```

2023-06-26 00:29 UTC, emteknetnz commented on src/Schema/Storage/CodeGenerationStore.php
> -use SilverStripe\GraphQL\Schema\Logger;
Prefer not to remove all of these in this PR since it's not related to the current issue.  Presumably they're not actually used and this is obvious in your IDE, though it's not obvious when looking at this pull-request in github

If we are to remove unused imports, I'd much prefer to bulk to this in a dedicated issue

2023-06-26 02:03 UTC, GuySartorelli commented on src/Schema/Storage/CodeGenerationStore.php
> -use SilverStripe\GraphQL\Schema\Logger;
Fair enough. Easy enough to view the file as a whole and ctrl+f to check against them but I'm fine with removing these changes from this PR.

2023-06-26 02:16 UTC, GuySartorelli commented on src/Schema/Storage/CodeGenerationStore.php
> -use SilverStripe\GraphQL\Schema\Logger;
Done

2023-06-26 02:16 UTC, GuySartorelli commented on src/Schema/Storage/CodeGenerationStore.php
> +    private function createNewTempSchema(FileSystem $fs, string $tempDir)
Done

2023-06-26 02:16 UTC, GuySartorelli commented on src/Schema/Storage/CodeGenerationStore.php
> +        } else {
> Seems a bit weird that we're splitting the code path here? ... why aren't we aren't we just treating the that dir the same way we currently treat `BASE_PATH/.graphql-generated`

The schema is _always_ initially built in the temporary directory. `getTempDirectory()` gets a directory path inside the silverstripe-cache directory.
Since the temp directory is already in `silverstripe-cache`, I opted to just use that as the directory for when `dirName` is set to an empty string/null. And since the temp directory then _is_ the final destination for the schema, there's no sense in copying the files from itself to itself. This is also why the second branch logs 'Using temporary directory for schema' and 'Creating new schema which will override any old schema'.

> In particular there's the line `$fs->mirror($dest, $temp);` which is only present in the `dirNameIsDefined()` code path, I'm not sure what this line is supposed to do

`$fs->mirror($dest, $temp);` copies all of the files from the _non temporary_ directory (normally `.graphql-generated/`) into the temp directory (hence why it logs 'Moving current schema to temp folder')

2023-06-26 02:16 UTC, GuySartorelli commented on src/Schema/Storage/CodeGenerationStore.php
> +        } else {
Is the above reasonable to you? Or would you prefer we still have a temporary directory _separate_ to the destination directory even when the destination directory is inside `silverstripe-cache/`? Happy to do either.

2023-06-26 23:58 UTC, emteknetnz commented on src/Schema/Storage/CodeGenerationStore.php
> +        } else {
OK makes sense, leave it as is

2023-06-26 23:58 UTC, emteknetnz approved these changes

2023-06-26 23:59 UTC, emteknetnz commented
Tested locally, works good

2023-06-27 00:00 UTC, emteknetnz commented
Opps accidentally closed it - I somehow mistook the close button for the merge button :-)

2023-06-27 00:40 UTC, merged