FIX Handle using injected subclasses
silverstripe/silverstripe-graphql pull request #549
Opened 2023-08-15 05:30 UTC by emteknetnz

Issue - https://github.com/silverstripe/silverstripe-graphql/issues/524

Original fix - https://github.com/wilr/silverstripe-graphql/commit/623bc9833039996c0c52f1a756b753730923e2b4

2023-08-15 22:15 UTC, GuySartorelli commented on src/Schema/DataObject/InheritanceBuilder.php
> +            }
I'm struggling to understand this condition... how would the ancestor ever be the same as the current model? I can't do a full review on this without understanding the conditions that happens under.

2023-08-16 01:01 UTC, emteknetnz commented on src/Schema/DataObject/InheritanceBuilder.php
> +            }
Condition is when Injector overrides a class with a subclass.  

Using the replication code in the original description - https://github.com/silverstripe/silverstripe-graphql/issues/524

At line 58 - you'll have the following:

```
$ancestors = [
  'App\Pages\SomePage',
  'Page',
  'Silverstripe\CMS\Model\SiteTree'
];

$ancestor = 'App\Pages\SomePage';

$modeType->getName() => 'PageExtendingSomePage"
$ancestorModel->getName() => 'PageExtendingSomePage"
```

Basically because of the injection `$ancestorModel->getName()` returns the name of the subclass, rather than the name of the baseclass

2023-08-16 23:45 UTC, GuySartorelli requested changes

2023-08-16 23:45 UTC, GuySartorelli commented on src/Schema/DataObject/InheritanceBuilder.php
> +        }
```suggestion
        $ancestorModel = null;
        foreach ($ancestors as $ancestor) {
            $ancestorModel = $this->getSchema()->findOrMakeModel($ancestor);
            if ($ancestorModel && $ancestorModel->getName() !== $modelType->getName()) {
                break;
            }
            $ancestorModel = null;
        }
        if (!$ancestorModel) {
            return;
        }
```
Even if there's an ancestor in the `$ancestors` array, if we don't find an ancestor that _isn't_ identical (due to injection) to the current `$modelType`, we don't want do any of the rest of this stuff.

Also swapped the condition around, so instead of "break if we don't continue", we only break once we've found an ancestor. This is a more intuitive flow.

2023-08-16 23:45 UTC, GuySartorelli commented on src/Schema/DataObject/InheritanceBuilder.php
>          }
```suggestion
```
No longer needed - if it's empty, we simply won't do anything in the loop, and `$ancestorModel` will remain null, so we'll be returning at that point.

2023-08-16 23:45 UTC, GuySartorelli commented on src/Schema/DataObject/InheritanceBuilder.php
> +        }
```suggestion
        $this->fillAncestry($ancestorModel);
```
The changes above mean we won't ever get in this scenario by the time we get down here, which makes the flow a little cleaner.

2023-08-17 06:07 UTC, emteknetnz commented on src/Schema/DataObject/InheritanceBuilder.php
> +        }
Ah, I think while this seems seems like simple inverted logic to make it read better, I think this may introduce an error in some scenarios.  I'm not entirely sure so I'm inclined to not change it right now.

The 
```
if (!$ancestorModel) {
    return;
}
```
Should probably actually throw an exception as previously it would fail when it would go `$ancestorModel->getFieldByName`.  However you could also been in a weird situation $ancestorModel is null, though $modelTypes->getFields() is an empty array so you never actually get to that point.

I don't know, I'm just speculating for stuff that might happen

I think I'd prefer to just leave as and not risk causing additional regressions here.

2023-08-17 06:08 UTC, emteknetnz commented on src/Schema/DataObject/InheritanceBuilder.php
> +        }
Not changing logic above, so not changing here either

2023-08-18 00:19 UTC, GuySartorelli commented on src/Schema/DataObject/InheritanceBuilder.php
> +        }
Lets talk about this offline - there's a lot going on here and there are definitely some changes required (the `if ($modelType->getName() !== $ancestorModel->getName()) {` condition at the bottom could result in some ancestry further up the chain not being processed, or at least _looks_ like it could which is arguably just as bad) - but we should work out whether the problem you've perceived with my recommendation is real or otherwise avoidable.

2023-08-18 00:23 UTC, GuySartorelli requested changes

2023-08-18 00:23 UTC, GuySartorelli commented on src/Schema/DataObject/InheritanceBuilder.php
> +        }
The `findOrMakeModel()` method _cannot_ return null. It's got a concrete return type of `ModelType`. So before if we'd had a `if (!$parentModel)` condition, it simply would never have been true.

The scenario you're describing was impossible before, and will only be possible now because in my suggestion we _explicitly_ set the variable to null in scenarios where the model we have for that variable is not value for the logic that follows.

2023-08-21 01:49 UTC, emteknetnz commented on src/Schema/DataObject/InheritanceBuilder.php
> +        }
> The scenario you're describing was impossible before, and will only be possible now because in my suggestion we explicitly set the variable to null in scenarios where the model we have for that variable is not value for the logic that follows.

I don't understand this sentence

Feels like we're dragging this out for the sake of making some code that works read a little nicer? This PR has a test showing things work as they should, can't we just merge this as is?

2023-08-21 07:01 UTC, GuySartorelli commented on src/Schema/DataObject/InheritanceBuilder.php
> +        }
That sentence basically says: You described a scenario that you think should throw an exception. The scenario where your `if (!$ancestorModel)` condition resolves to `true` wasn't possible before this PR, nor in this PR as it currently stands. The only reason it will potentially resolve to `true` _with_ my suggested change is because we _explicitly_ set it to null. The actual returned value from `findOrMakeModel()` will _never_ be null, so we don't need to worry about that. There was never a scenario where we would have gotten to `$ancestorModel->getFieldByName()` where `$ancestorModel` was null in your current PR, nor prior to this PR if we exchange `$ancestorModel` for `$parentModel`.

It is a response to "I don't know if any of this stuff would happen, I'm just speculating for stuff that might happen" - basically, none of that stuff _would_ nor _could_ happen.

> Feels like we're dragging this out for the sake of making some code that works read a little nicer?

Nope. I'm recommending this change in part because it increases code readability, in part because it reduces _confusion_, and in part because it reduces _complexity_. It is an all-round good suggestion that make the code easier to maintain and I can't see any reason to _not_ apply the change. Please apply the change.

2023-08-21 23:56 UTC, emteknetnz commented on src/Schema/DataObject/InheritanceBuilder.php
> +        }
done

2023-08-21 23:56 UTC, emteknetnz commented on src/Schema/DataObject/InheritanceBuilder.php
> +        }
done

2023-08-21 23:56 UTC, emteknetnz commented on src/Schema/DataObject/InheritanceBuilder.php
>          }
done

2023-08-22 02:39 UTC, GuySartorelli approved these changes
Looks good to me

2023-08-22 02:39 UTC, merged