ENH add canInit method and CAN_DEV_GRAPHQL permissions
silverstripe/silverstripe-graphql pull request #559
Opened 2023-10-19 01:18 UTC by andrewandante

Companion PR to https://github.com/silverstripe/silverstripe-framework/pull/10979
Aims to solve https://github.com/silverstripe/silverstripe-framework/issues/10852

Adds a fine-grained permission for `/dev/graphql`

2023-10-19 09:27 UTC, andrewandante commented
Test failures are for a missing method that's contained in the companion PR: `DevelopmentAdmin::permissionsCategory()`

2023-10-19 20:02 UTC, GuySartorelli reviewed
If this will require a method that doesn't exist until framework 5.2, we need to bump the dependency in composer.json

2023-10-25 21:38 UTC, GuySartorelli requested changes
Please also apply any relevant feedback from the framework PR.

2023-10-25 21:38 UTC, ChloeSartorelli commented on src/Dev/DevelopmentAdmin.php
> +                'name' => _t(__CLASS__ . '.CAN_DEV_GRAPHQL_DESCRIPTION', 'Can access GraphQL tools'),
```suggestion
                'name' => _t(__CLASS__ . '.CAN_DEV_GRAPHQL_DESCRIPTION', 'Can access /dev/graphql'),
```
This is consistent with the wording of permissions in the other PR.

2023-11-07 21:29 UTC, GuySartorelli approved these changes
LGTM, works as expected. Will merge when the framework PR has been merged.

2023-11-10 00:20 UTC, GuySartorelli commented
Rerunning CI - will merge on green

2023-11-10 01:00 UTC, merged