MNT Fix broken build
silverstripe/silverstripe-graphql pull request #562
Opened 2023-11-14 07:21 UTC by sabina-talipova

## Description

2023-11-20 04:43 UTC, GuySartorelli requested changes
This can't be `MNT` since it's changing actual code that projects will be using.

If the changes in the `QuerySort` class are fixing a bug, you should use `FIX` and the commit message should explain what the bug is that's being fixed.
If they're just an enhancement, then use `ENH` and the commit message should explain what the enhancement is.

2023-11-20 20:56 UTC, GuySartorelli commented on tests/Schema/_testFilterAndSort/models.yml
> +    myField: true
Does this change actually affect the test at all?

2023-11-20 21:19 UTC, GuySartorelli commented on tests/Schema/_testFilterAndSort/models.yml
> +    myField: true
Talked offline - this does apparently affect the tests. I'll see if I can find out what's going on there because this shouldn't affect the sort order, especially given we're explicitly sorting in the query.

2023-11-21 01:23 UTC, GuySartorelli commented
The reason changing the order of the fields in the schema affected the results is because the underlying GraphQL library we're using ignores the order that fields are entered in the query arguments. It uses the order that the fields were defined in the schema.

I've added a new commit on top of yours to resolve this. It also changes the test to use a query provider so it will run all of the FilterAndSort scenarios even if one fails. I removed the scenarios that had commented out tests because they weren't actually contributing anything to the test coverage.

## Next steps

1. Have a look over this code and test it locally to make sure you're happy with it. This is still your PR, so make any changes you think are appropriate.
2. Add new test coverage to check this works correctly with a normal `read` (not read one - but read many) query
3. See if changes similar to what I've made are necessary in `src/Schema/Plugin/SortPlugin.php`

2023-11-21 01:24 UTC, GuySartorelli commented on src/Schema/DataObject/Plugin/QuerySort.php
> +        return function (?Sortable $list, array $args, array $context, ResolveInfo $info) use ($fieldName, $rootType) {
Since this is an anonmyous function, it's not part of our public API, so we can add arguments without breaking backwards compatability.

2023-11-21 01:27 UTC, GuySartorelli commented
Please also check if this bug affects graphql 4 - if so, we need to retarget to `4.3`

2023-11-22 20:54 UTC, closed without merging

2023-11-22 20:55 UTC, sabina-talipova commented
Open new PR for 4.3:
- https://github.com/silverstripe/silverstripe-graphql/pull/563