MNT Add test cases for SortPlugin
silverstripe/silverstripe-graphql pull request #564
Opened 2023-11-26 19:34 UTC by sabina-talipova

## Parent issue
-

2023-11-26 20:12 UTC, GuySartorelli requested changes
You have only one test validating that this sort plugin works when sorting multiple fields at once:
`files(sort: { name: ASC, title: DESC }) {`

Please also add one with those fields reversed, to validate that the order in which the fields are added _in the query_ changes the actual sort order.
`files(sort: { title: DESC, name: ASC }) {`
Make sure this new scenario gives different results than the existing one.

2023-11-27 20:15 UTC, GuySartorelli requested changes
Since this is now a bugfix, please update the commit message to use the `FIX` prefix and to have a message that explains what bug is being fixed.

2023-11-27 20:15 UTC, ChloeSartorelli commented on src/Schema/Plugin/SortPlugin.php
> +            $sortArgs = static::getSortArgs($info, $args, $fieldName);
```suggestion
            $sortArgs = self::getSortArgs($info, $args, $fieldName);
```
Since it's a private method, `static` is effectively the same as `self` in this scenario - this is a bit of a nitpick but it's nicer to explicitly call private statics on `self` to avoid the appearance that there's some magic allowing a different method to be called on the subclass.

2023-11-27 20:15 UTC, ChloeSartorelli commented on src/Schema/Plugin/SortPlugin.php
>              }
Return early if there's no sort argument for this query.
```suggestion
            }

            if (!isset($args[$fieldName])) {
                return $list;
            }
```

2023-11-27 20:15 UTC, ChloeSartorelli commented on src/Schema/Plugin/SortPlugin.php
> +    }
Since this is identical to the code in `src/Schema/DataObject/Plugin/QuerySort.php`, move the code into a new trait and use the trait in both classes. This way if we find some fault in the logic later on we can fix it in both places at the same time.

2023-11-27 20:59 UTC, sabina-talipova commented on src/Schema/Plugin/SortPlugin.php
> +            $sortArgs = static::getSortArgs($info, $args, $fieldName);
Updated

2023-11-27 20:59 UTC, sabina-talipova commented on src/Schema/Plugin/SortPlugin.php
>              }
Updated

2023-11-27 20:59 UTC, sabina-talipova commented on src/Schema/Plugin/SortPlugin.php
> +    }
Updated

2023-11-27 21:59 UTC, GuySartorelli requested changes
Just one small change - everything else looks good.

2023-11-27 21:59 UTC, GuySartorelli commented on src/Schema/Traits/SortTrait.php
> +namespace SilverStripe\GraphQL\Schema\Traits;
```suggestion
namespace SilverStripe\GraphQL\Schema\Plugin;
```
Please move this into the `Plugin/` directory - we don't need a whole directory for traits.

2023-11-27 22:11 UTC, sabina-talipova commented on src/Schema/Traits/SortTrait.php
> +namespace SilverStripe\GraphQL\Schema\Traits;
Since both sort plugins located in different directories `SilverStripe\GraphQL\Schema\DataObject\Plugin\QuerySort` and `SilverStripe\GraphQL\Schema\Plugin\SortPlugin`, probably it would be better to leave trait in common directory for now, while we have not decided about future architecture of our plugins.

2023-11-27 22:13 UTC, ChloeSartorelli commented on src/Schema/Traits/SortTrait.php
> +namespace SilverStripe\GraphQL\Schema\Traits;
Ahh yup good call. Didn't notice there were two plugin directories.

2023-11-27 23:19 UTC, GuySartorelli approved these changes
LGTM

2023-11-27 23:19 UTC, merged