FIX: Don't attempt to correct sort when passed as an argument (closes #571)
silverstripe/silverstripe-graphql pull request #577
Opened 2024-02-28 17:06 UTC by kinglozzer

## Description
Proposed fix for #571. Doesn’t actually solve the underlying issue, but prevents the warnings being emitted by `SortTrait`.

## Manual testing steps
N/A

## Issues
- #571

## Pull request checklist

- [ ] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [ ] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [ ] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [ ] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [ ] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [ ] This change is covered with tests (or tests aren't necessary for this change)
- [ ] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [ ] CI is green

2024-02-28 17:08 UTC, lozcalver commented on tests/Schema/IntegrationTest.php
> +        });
This test has been added to ensure that sort args can be used without throwing warnings, so I’m just forcing the same sort order here

2024-03-04 15:23 UTC, kinglozzer commented on tests/Schema/IntegrationTest.php
> +        });
Turns out there’s an assertion for this, `assertEqualsCanonicalizing()`, so I’ve switched to that instead

2024-04-19 01:52 UTC, marwan38 commented
Bump. This issue is completely breaking one of my queries

2024-05-06 21:15 UTC, GuySartorelli requested changes

2024-05-06 21:15 UTC, GuySartorelli commented on tests/Schema/IntegrationTest.php
> +GRAPHQL,
Can you please revert the indentation to be what it was before?
For this and all other HEREDOC you've touched in this PR.

2024-05-06 21:15 UTC, GuySartorelli commented on tests/Schema/IntegrationTest.php
I haven't done a thorough review of this test - but at a glance it looks like there's one less test scenario than there was before?

2024-05-06 21:15 UTC, GuySartorelli commented on src/Schema/Traits/SortTrait.php
> +                }
What are the circumstances that result in the value not being an instance of that class?
Depending on what those circumstances are, we might want to throw an exception (or at the very least log a warning) if someone tries to perform a sort that we explicitly don't respect here.

2024-05-08 08:36 UTC, kinglozzer commented on src/Schema/Traits/SortTrait.php
> +                }
`$arg->value` is only ever an instance of `ObjectValueNode` when the sort order is baked into the query, so the `continue` statement is reached when sort is passed as a variable instead.

2024-05-08 08:46 UTC, kinglozzer commented
@GuySartorelli a little more context: there are two ways to pass a sort order: (1) baked directly in to the query itself, or (2) as an argument.

For (1), #563 was merged to ensure that the order that you provide sort fields is respected. A regression from that PR is that when you use approach (2), a warning is thrown.

For (2), #563 had no effect anyway. This PR just ensures that when using this approach, the warning isn’t thrown and everything behaves as it did before #563 was merged.

Ideally, we’d expand #563 to cover both approaches to sorting. However that isn’t possible, because the underlying GraphQL library discards the order that sort fields are passed in when parsing the query. That isn’t a bug with the library, it’s actually the intended behaviour as it respects the GraphQL spec. There‘s some more info in #573 about that, but that’s a much bigger job and would have to be targeted at a major release.

2024-05-08 21:41 UTC, GuySartorelli commented
Thank you for that extra context. I think in that case I'm okay with this - but a warning needs to be logged so developers can get some feedback that their query isn't working as intended.

2024-05-09 08:20 UTC, kinglozzer commented
> a warning needs to be logged so developers can get some feedback that their query isn't working as intended

I’m not really sure how to tackle that, the warning is the problem... we could possibly use a custom logger and call `$logger->info()` but unless the logger is set up to actually record that somewhere, nobody will ever see it.

2024-05-09 08:24 UTC, GuySartorelli commented
We should log a warning using the `Psr\Log\LoggerInterface.errorhandler` singleton.

> unless the logger is set up to actually record that somewhere, nobody will ever see it.

Yup, that's true of all logging. Better give the option than nothing though.

2024-05-22 13:16 UTC, kinglozzer commented
I’ve finally got around to this. Using `LoggerInterface::class . '.errorhandler'` results in the warning being output in the HTTP response, which breaks everything, so I’ve copied the approach from the old file migration task: https://github.com/silverstripe/silverstripe-assets/blob/1.13/_config/migration.yml. Essentially it’s a logger instance that doesn’t include an output handler so nothing appears in the HTTP output, but the warning is still logged to the error log

2024-05-23 00:31 UTC, GuySartorelli approved these changes
LGTM, thanks for doing this.

2024-05-23 00:31 UTC, merged