API Add Directive types
silverstripe/silverstripe-graphql pull request #580
Opened 2024-04-13 10:57 UTC by marwan38

Hi, this is a [nearly] complete PR adding in the directive type. 

Questions for the maintainers:

SchemaTransciber does not introspect the directives. Therefore users relying on the schema transcriber won't be able to get the full schema including the directives. I can't make the decision on behalf of the framework on how much you want added within the introspection query.  I personally don't use it, we generate the schema directly using @graphql-codegen and that introspects what we need. An example of a more comprehensive introspection query can be found [here](https://github.com/graphql/graphql-js/blob/main/src/utilities/getIntrospectionQuery.ts#L41) and what the directives field may contain [here](https://github.com/graphql/graphql-js/blob/main/src/utilities/getIntrospectionQuery.ts#L76). That introspect query also adds the complexity of configuration, so I'm not really sure what you guys would want here. As I said, this feature as-is is enough for me at the moment.

There's not much coverage on the tests apart from type creation. This PR only adds defining the directive, which is only a matter of (1) defining the directive type and (2) the graphql server being able to parse it and expose it through `ResolveInfo`. I'm not too sure how to test that within this codebase, would appreciate a bit of insight. The test would look something like:
```php
$directive = Directive::create('myDirective', []);
$mock = $this->getMockBuilder(GraphQLSchema::class)
  ->setMethods(['setDirectives'])
   ->getMock;
   
$mock
    ->expects($this->once())
    ->method('setDirectives')
    ->with(\GraphQL\Type\Definition\Directive::class);
)
```

## Description

Directives are part of the GraphQL specification and this PR adds the Directive type for developers to create custom ones.

## Manual testing steps

A new type is added `directives` in the graphql schema yaml file.
```yaml
---
directives:
  myDirective:
    description: 'Optional description'
    args:
      if:
        type: Boolean
        defaultValue: true
    locations: [QUERY]
```

Viewing the schema in the graphql schema should now contain an entry like so:
```
# Optional description
directive @myDirective(if: Boolean = true) on QUERY
```

The configuration of the `Directive` type can be found here https://webonyx.github.io/graphql-php/type-definitions/directives/#custom-directives.

## Issues

- #578

## Pull request checklist

- [x] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [x] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [x] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [ ] This change is covered with tests (or tests aren't necessary for this change)
- [ ] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [ ] CI is green

2024-04-13 11:57 UTC, marwan38 commented on src/Schema/Storage/templates/registry.inc.php
> +
This probably breaks some PSR specs, I'm not sure if it matters here or not?

2024-04-23 05:06 UTC, GuySartorelli requested changes
Please add a PR to https://github.com/silverstripe/developer-docs as well, adding documentation for this new feature.

The documentation will be necessary for other developers to take advantage of this - but it's also a way I can make sure I'm testing it correctly. If I follow the documentation and things don't work as expected, it's clear something (either the documentation or the implementation) isn't working as expected.

I'm also still not sure what these directives *do* or what they're *for*... You've mentioned they're "part of the GraphQL specification" and that they're "a fundamental part of GraphQL" but not much more. Can you please briefly explain what this feature actually is, and why it is useful?

2024-04-23 05:06 UTC, ChloeSartorelli commented on src/Schema/Storage/CodeGenerationStore.php
> +                    ';'
Why was this change made? It seems unrelated

2024-04-23 05:06 UTC, ChloeSartorelli commented on src/Schema/Storage/templates/registry.inc.php
> +
You say "this" on a comment on an empty line... but I assume you are actually referring to having multiple classes defined in the same file?

That does break PSR1 (see [the PSR1 spec](https://www.php-fig.org/psr/psr-1/#3-namespace-and-class-names)).
Ideally each of these templates should be explicitly for a single class.

One approach would be to reuse the same template file (with only one clsas definition) for both of these since they're practically identical, and just add appropriate conditional statements. e.g. type.inc.php uses a lot of conditional logic to build its class.

2024-04-23 05:06 UTC, GuySartorelli commented on tests/Schema/IntegrationTest.php
> +        $this->assertSuccess($result);
Please add an assertion for the result as well - presumably the directive should add something to the result which we can test for.

2024-05-23 23:17 UTC, GuySartorelli commented
@marwan38 This PR hasn't been updated for a while. Are you still keen for this feature to be included?
If so please address the comments above. If not, I will close this PR.

2024-05-27 11:24 UTC, marwan38 commented
@GuySartorelli Yeah, still want it included. I've just not dedicated any time to it just yet. If you prefer to close this PR and bring up a new one when I'm ready; that's fine. 

There's a few bad commits in here for various different reasons (my own formatters, debug code, etc..).

2024-07-22 02:51 UTC, GuySartorelli commented
Sweet. Yes, please feel free to open a new PR when you have a chance to work on this - but I'll close it for now.

2024-07-22 02:51 UTC, closed without merging