MNT Move config from silverstripe/admin so that unit-tests pass
silverstripe/silverstripe-graphql pull request #596
Opened 2024-08-13 06:53 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-admin/issues/1799

2024-08-15 01:36 UTC, emteknetnz commented on tests/Middleware/CSRFMiddlewareTest.php
> +        // CSRF token check is normally disabled for unit-tests
This is needed because after moving the location of this test in recipe-kitchen-sink, some other test was somehow interfering with this.  This just sets up the Security token so that it's in the correct state for the test, and then resets it to however it was before

2024-08-20 03:42 UTC, GuySartorelli requested changes
I assume those docs are all just directly copy/pasted, and haven't been altered at all?
They may need retouching when they get added back into the "other features" section but there's a separate card for that so that's okay.

2024-08-20 03:42 UTC, GuySartorelli commented on _config/_versioned/config.yml
> +modelConfig:
These should be in `_graphql/versioned/` not `_config/_versioned/`
They're not config in the silverstripe/config sense.

2024-08-20 03:42 UTC, GuySartorelli commented on _config/asset-admin.yml
> +      Generates: false
This was explicitly only used inside asset admin, so we don't need to carry this over. Delete this IMO

2024-08-20 03:42 UTC, GuySartorelli commented on _config/versioned.yml
> +        versionedSrc: 'silverstripe/graphql: _config/_versioned'
```suggestion
        versionedSrc: 'silverstripe/graphql: _config/versioned'
```
I'm also not sure what that `silverstripe/graphql` bit does - if it still works when you remove that, you should probably remove it.

2024-08-21 03:52 UTC, emteknetnz commented on _config/asset-admin.yml
> +      Generates: false
Needed for AssetAdmin unit tests, and also anyone who wants to get the thumbnail urls via the resolver would presumably benefits from this

2024-08-22 05:19 UTC, GuySartorelli requested changes

2024-08-22 05:19 UTC, GuySartorelli commented on docs/en/01_getting_started/01_server_requirements.md
> +  the same way you treat the `.graphql-generated` folder.
```suggestion
- `.graphql-generated`: This directory is where your schema is
  stored once it [has been built](/developer_guides/graphql/getting_started/building_the_schema). Best practice
  is to create it ahead of time, but if the directory doesn't exist and your project root is writable, the GraphQL
  module will create it for you.
- `public/_graphql`: This directory is used for
  [schema introspection](/developer_guides/graphql/tips_and_tricks#schema-introspection). You should treat this folder
  the same way you treat the `.graphql-generated` folder.
```
No need to say this module uses it - it's in this module's docs!

2024-08-22 05:19 UTC, GuySartorelli commented on docs/en/01_getting_started/01_server_requirements.md
Links here are incorrect

2024-08-22 06:28 UTC, emteknetnz commented on docs/en/01_getting_started/01_server_requirements.md
> +  the same way you treat the `.graphql-generated` folder.
Updated

2024-08-22 07:14 UTC, emteknetnz commented on docs/en/01_getting_started/01_server_requirements.md
Updated, they *should* work once we add included these docs on docs.silverstripe.org as an optional module similar to elemental and linkfield

2024-08-22 22:51 UTC, GuySartorelli approved these changes
LGTM will merge when other PRs are happy

2024-09-02 03:20 UTC, GuySartorelli approved these changes
re-approved most recent changes

2024-09-02 04:33 UTC, merged