MNT Fix test that didn't account for i18n spaces
silverstripe/silverstripe-graphql pull request #611
Opened 2024-09-26 23:50 UTC by GuySartorelli

Fixes https://github.com/silverstripe/silverstripe-graphql/actions/runs/11061549418/job/30734504257?pr=610

> 1) SilverStripe\GraphQL\Tests\Schema\IntegrationTest::testDBFieldArgs
> Failed asserting that two strings are equal.
> --- Expected
> +++ Actual
> @@ @@
> -'2/29/20, 5:00 PM'
> +'2/29/20, 5:00 PM'

The date formatter used is `IntlDateFormatter` which sometimes uses narrow non-breaking spaces. These are valid, given the intention of using `IntlDateFormatter` is to give a format that is correct for the locale used on the front-end, and in some locales the narrow non-breaking space is correct.

This test doesn't have to care what specific spaces are used - just that the correct date is there in the correct format.

## Issue
- https://github.com/silverstripe/.github/issues/313

2024-09-26 23:50 UTC, GuySartorelli commented
lint failure is unrelated and will be fixed by https://github.com/silverstripe/silverstripe-graphql/pull/610

2024-09-29 23:14 UTC, emteknetnz requested changes

2024-09-29 23:14 UTC, emteknetnz commented on tests/Schema/IntegrationTest.php
> +        $this->assertMatchesRegularExpression('#2/29/20,\h5:00\hPM#u', $node['date2']);
This seems wrong, SapphireTest should be [setting](https://github.com/silverstripe/silverstripe-framework/blob/5/src/Dev/SapphireTest.php#L285) the i18n default locale to [en_US](https://github.com/silverstripe/silverstripe-framework/blob/5/src/i18n/i18n.php#L80).

2024-09-29 23:19 UTC, emteknetnz commented on tests/Schema/IntegrationTest.php
> +        $this->assertMatchesRegularExpression('#2/29/20,\h5:00\hPM#u', $node['date2']);
Actually it might be html5 overriding it - https://github.com/silverstripe/silverstripe-framework/blob/5/src/Forms/DateField.php#L450

However there's a [comment](https://github.com/silverstripe/silverstripe-framework/blob/5/src/Forms/DateField.php#L108) that this should force a particular standard of date formats, so even then we still shouldn't get thin spaces?

2024-09-29 23:19 UTC, GuySartorelli commented on tests/Schema/IntegrationTest.php
> +        $this->assertMatchesRegularExpression('#2/29/20,\h5:00\hPM#u', $node['date2']);
This one is draft for a reason.

2024-09-30 00:56 UTC, GuySartorelli commented on tests/Schema/IntegrationTest.php
> +        $this->assertMatchesRegularExpression('#2/29/20,\h5:00\hPM#u', $node['date2']);
Based on https://github.com/php/php-src/issues/11600 it seems that there was an intentional change in "ICU" which seems to be what's used under-the-hood for the i18n date formatting. This change includes the narrow non-breaking spaces which seem like they're here to stay.

We'll need to update a bunch of tests to account for it, including this one.

2024-09-30 05:32 UTC, emteknetnz approved these changes

2024-09-30 05:32 UTC, emteknetnz requested changes
Linting failure

2024-09-30 20:06 UTC, GuySartorelli commented
https://github.com/silverstripe/silverstripe-graphql/pull/611#issuecomment-2378132987

2024-09-30 20:37 UTC, emteknetnz approved these changes

2024-09-30 20:37 UTC, merged